### ISSUE TITLE
3.x and dynamic validation

### ISSUE THREAD

**Issue by bufke** [MrWolfZ/ngrx-forms#100]
Hello,

I'm implementing a change password form where the new password should have validation to ensure it's not the old password. It looks like:

```
export const validateAndUpdateFormState = updateGroup<IChangePasswordForm>({
  oldPassword: validate([...passwordValidators]),
  newPassword: (newPassword, form) => {
    return validate(newPassword, [
      ...passwordValidators,
      notEqualTo(form.value.oldPassword)
    ]);
  },
});
```

I had this working in 2.x and actually this code works in 3.x too except it raises a typescript error. 

```
Argument of type '{ oldPassword: (state: AbstractControlState<string>) => FormControlState<string>; newPassword: (n...' is not assignable to parameter of type 'StateUpdateFns<IChangePasswordForm>[]'.
  Object literal may only specify known properties, and 'oldPassword' does not exist in type 'StateUpdateFns<IChangePasswordForm>[]'.
```

Reading https://github.com/MrWolfZ/ngrx-forms/issues/97 I suspect the issue is "you get that error is that there is an overload on updateGroup that takes the form state as the first parameter and if typescript cannot match the overload it defaults to the first one. "

Am I doing something strange here? Is it possible the type definitions are incorrect?

**Comment by MrWolfZ** [comment]
With v3 I changed the validate function to take an array or rest params of validation functions. However, overload resolution seems to be a bit iffy with that. Can you try removing the square brackets and just spread the password validators into the validate call directly?

**Comment by bufke** [comment]
It doesn't help, even a simple version like this `oldPassword: validate(required),` gets the same error. I uploaded the work in progress in case you'd like to see.

https://gitlab.com/passit/passit-frontend/blob/ngrxforms3/src/app/account/change-password/change-password.reducer.ts#L52

Just running `yarn` and `yarn start` (or opening in VS Code) should show the TS error.

Removing the newPassword part makes it the error go away as does making newPassword something simple like validate(required). I would guess the existence of the field: (x, y) => code causes it to pick one type def over another and ultimately error.

**Comment by bufke** [comment]
I've found a way to make it work - based on reading #97 I thought `validate<type>` was no longer needed. However If I change my snippet to 

```
export const validateAndUpdateFormState = updateGroup<IChangePasswordForm>({
  oldPassword: validate([...passwordValidators]),
  newPassword: (newPassword, form) => {
    return validate<string>(newPassword, [
      ...passwordValidators,
      notEqualTo(form.value.oldPassword)
    ]);
  },
});
```

The TS errors go away. The change is the <string> in the return of the password validation function.

This solves the issue for me, there may be something fishy going on with types still. Up to you if you'd like to keep this ticket open or not.

As always thanks for your time and for the project.

**Comment by MrWolfZ** [comment]
Hmm, even though you found a workaround it should work without specifying the type. I remember having some issues getting the typing right for the `validate` update function. Let's keep this issue open and I'll see if I can improve the typing.

**Comment by MrWolfZ** [comment]
Alright, I had a quick look at your code. I could make it work with a single type annotation. The reason that is required is due to `oldPasswordValidators` not being typed as an array of string validation functions. Since `required` can take any value and `minLength` can take `string | any[] | null | undefined` the `oldPasswordValidators` is inferred as `(<T extends string | any[] | null | undefined>(value: T) => ValidationErrors)[]`. And therefore the form update object has the wrong type. The fix is to either specify the type at the validate call as you did (and is shown below) or to type the validator array specifically, i.e. `export const oldPasswordValidators: ValidationFn<string>[] = [required, minLength(6)];`. The reason it worked before was due to a more constrained parameter type support for the validate function and other functions. With the new inference features of v3 that won't work. I don't think I can fix this so I'll close the issue.

```typescript
export const validateAndUpdateFormState = updateGroup<IChangePasswordForm>({
  oldPassword: validate<string>(oldPasswordValidators),
  newPassword: (newPassword, form) => {
    return validate(newPassword, [
      ...passwordValidators,
      notEqualTo(form.value.oldPassword),
    ]);
  },
  newPasswordConfirm: (passwordConfirm, form) => {
    if (form.controls.showConfirm.value) {
      return validate(
        passwordConfirm,
        required,
        equalTo(form.value.newPassword)
      );
    }
    return validate(passwordConfirm, []);
  },
});
```
