### ISSUE TITLE
possible to provide custom template for typeahead items?

### ISSUE THREAD

**Issue by jmcmichael** [MrWolfZ/ngrx-forms#104]
I have a selector with items that are generated from an array of objects containing several attributes of interest to the user. In addition to the typeahead dropdown displaying the attribute specified by 'bindLabel', I'd like to additionally display another attribute value on the same object in smaller text below the bindLabel attribute value.

Is it possible to create a template with the additional content to replace the default template?

**Comment by MrWolfZ** [comment]
I’m not sure I understand what you mean. ngrx-forms only handles state management, it is not involved with rendering at all. Therefore it as no impact on any labels and such.

Are you using a third-party typeahead component? If so I recommend asking in their repository.

**Comment by jmcmichael** [comment]
Ah, yes indeed - I'm working on a form based on ngrx-forms and the ng-select component - I'd hit the wrong tab before opening this issue, apologies.

Fabulous library, btw - I'm finding it helpful for the same kinds of features that angular-formly provided for AngularJS.
