### ISSUE TITLE
Validation of material datepicker

### ISSUE THREAD

**Issue by codemasterover9000** [MrWolfZ/ngrx-forms#109]
Hi,

I use Material datepickers in my forms  in conjunction with MomentDateAdapter. When I input an invalid date ("abcd" for example) the value the form reducer receives from the material datepicker is null. In my specific case this is a valid value. So the validation returns no errors while the input is clearly incorrect.

What happens is that the datepicker recognizes the incorrect input and sets the error state. The reducer undo's this because it gets a valid value null instead of the actual input "abcd". The CustomErrorStateMatcherDirective resets the error state.

Im not sure how to handle this case? Any ideas?

Thanks in advance!

**Comment by MrWolfZ** [comment]
Hmm, the only thing that comes to mind would be to add `(input)=setUdpOnControl($event.target.value)` on the `input` element and inside your component dispatch an action that sets a user defined property on the form control. By accessing the `input`'s value this way you side-step the moment date adapter. Inside your validation function you can then check for this user defined property and add the proper validation error.

**Comment by codemasterover9000** [comment]
I tried your suggestion. But that only works for a user's manual input not for programmatically set values. What I did in the end was make a custom DateAdapter<string> based on MomentDateAdapter.
