### ISSUE TITLE
Dynamic validation rules

### ISSUE THREAD

**Issue by dankerk** [MrWolfZ/ngrx-forms#114]
Hi there,

I want to validate my form fields based on a set of validation rules that may change when some form values are updated.

To get the new rules I send a request to a service, then it should revalidate most of the fields in the form. 
The validations themselves are synchronous, but I need to get the rules from a service.
I also need acces to the parent state as to get 2 values that I need to pass to the service.

How can/should I access the store and how can I call a service from within my form reducer?

I can do it with an effect but I'm getting stuck because I can only validate 1 field at a time with an Effect... or can I?

I suppose one way of doing it would be to dispatch an action that contains all the validation rules and capture that in the reducer. Does that makes sense?

I could also set the validation rules in the store, but then, how would I access them from my reducer?

**Comment by MrWolfZ** [comment]
The last two of your options would be my recommendation, i.e. to:

- create an effect that listens to form value changes, performs the server call and dispatches an action containing the updated validation rules
- store the validation rules in the store where your form state lives or store them as a user-defined property on the form state itself
- parameterize the validation function with the validation rules (if they are stored outside of the form state) or access the rules inside the validation function (if the rules are stored as user-defined properties)

The code could look roughly like this (using user-defined properties):

```typescript
interface MyFormValue {
  foo: string;
}

function myFormReducer(formState: FormGroupState<MyFormValue>, action: Action) {
  switch (action.type) {
    case 'set validation rules':
      formState = setUserDefinedProperty(formState, 'validationRules', (action as any).rules);
      return validateMyForm(formState);

    default:
      return validateMyForm(formStateReducer(formState));
  }
}

function validateMyForm(formState: FormGroupState<MyFormValue>) {
  const rules = formState.validationRules;
  return updateGroup(formState, {
    // apply the rules
  });
}
```

**Comment by dankerk** [comment]
MrWolfZ, you are a legend.
I was almost there but didn't think of storing the rules in the formState itself!
🌮 for you :)
