### ISSUE TITLE
Async reusable validators

### ISSUE THREAD

**Issue by MateWW** [MrWolfZ/ngrx-forms#121]
Hello,
I looking for idea how to create reusable async validation?
I took a look on example app and in my case i don't have any point where i can trigger async validation. In my opinion async validation should automaticly dispatch event when field is valid locally and any async validator is assigned.

Now it doesn't work very well IMO.

**Comment by MrWolfZ** [comment]
Hmm, providing ideas for re-usable async validation is tricky since there are so many different patterns on how people perform asynchronous actions. In the example application I am using effects, and therefore it may be possible to provide an observable transformation function that dispatches the correct action, something like this:

```typescript
import { required } from 'ngrx-forms/validation';

function validateRequiredAsync(input: Observable<any>, controlId: string): Observable<Action> {
  return input.pipe(
    map(required),
    map(errors => new SetAsyncErrorAction(controlId, 'required', errors)),
    startWith(new StartAsyncValidationAction(controlId, 'required')),
  );
}
```

In case you are using services you could do something similar, just dispatch the actions instead of returning them in the observable, i.e.:

```typescript
import { required } from 'ngrx-forms/validation';

// input is the observable from the service call
function validateRequiredAsync<T>(input: Observable<T>, controlId: string, actionsSubject: ActionsSubject): Observable<T> {
  return Observable.create(observer => {
    actionsSubject.next(new StartAsyncValidationAction(controlId, 'required'));
    return input.pipe(
      tap(value => actionsSubject.next(new SetAsyncErrorAction(controlId, 'required', required(value)))),
    );
  });
}
```

**Comment by MateWW** [comment]
Okay, maybe the answer to this question will be more helpful. How can I solve such problem. I do not have a specific place in the store for the form (the reducer is generic and can be used everywhere) and now I want to call asynchronous validation only if normal validators say that the value is correct.

**Comment by MrWolfZ** [comment]
I apologize for not responding sooner. I hope my answer can still provide some help. If you have already solved this please close the issue.

Regardless of where you trigger the async validation you will need to know the form control ID of the control you are trying to validate. This ID should be globally unique even if the reducer is used in multiple places. If you only want to trigger async validation if the sync validation is successful I would recommend doing this inside the component that contains the form. Inside of that component you have access to the form state and therefore its ID. You can then either subscribe to the store and set up a subscription to value and validity changes of the form (if using a smart component) or react to value and validity changes through `ngOnChanges` or by using a setter on the form state input binding. Regardless of how you do this you can then simply check whether the value changed and the sync validation was successful and dispatch the proper actions for triggering the async validation. I hope this helps.

**Comment by MrWolfZ** [comment]
Closed due to inactivity.
