### ISSUE TITLE
refresh action

### ISSUE THREAD

**Issue by fxck** [MrWolfZ/ngrx-forms#125]
I'm using this state update function to control whether a form control should be disabled or not, I'm using parent state (form group) to get to a value of sibling radio button's value to decide the disabled state.

```typescript
    accessToClientZone: (s, ps) => {
      if (ps.value.roleCode === ClientUserRoles.Manager) {
        return disable(setValue(s, true));
      }
      return enable(s);
    }
```

Now sometimes I would like use value not from only the parent state, but from the whole store slice the form is sitting on. For example I have a `UserEdit` slice, which, along with `forms` property which contains by disabling control, has property `isDeleted: boolean;`, which should also control the disabled state, so ideally I'd like to do this:

```typescript
    accessToClientZone: (s, ps) => {
      if (ps.value.roleCode === ClientUserRoles.Manager || state.isDeleted) {
        return disable(setValue(s, true));
      }
      return enable(s);
    }
```

...and there is nothing preventing me from doing the.. the problem is, that this state update function runs only when ngrx-forms actions happens and by `state.isDeleted` can be changed by other forms unrelated actions..

I might be going best practices of this library and there are better ways to achieve this, but what I'm thinking is that ngrx-forms would expose "refresh" action, which I would dispatch for all of these state update functions to run with the current state.

What do you think @MrWolfZ ?

**Comment by fxck** [comment]
What I'm doing currently is dispatching `EnableAction`,  but the problem is that I have to do it for each group key for separate forms..

**Comment by MrWolfZ** [comment]
It all depends on how you call the state update function. If you are using `createFormStateReducerWithUpdate` then the update will indeed only run when something changes inside the form state. However, you can simply change this to be `updateFormState(formStateReducer(formState, action))` and your update will always be applied.

**Comment by fxck** [comment]
Yea, I'm indeed using `createFormStateReducerWithUpdate` and in most cases it's the desired behaviour, wouldn't it be worth adding that refresh action for more granular control anyway?

**Comment by MrWolfZ** [comment]
I'm not really sure what the refresh action is supposed to do. It wouldn't change the form state by itself, just in combination with that specific update pattern by forcing the update to run, right? Or is there something else you would expect the refresh action to do?

**Comment by MrWolfZ** [comment]
Closed due to inactivity.

**Comment by fxck** [comment]
> It wouldn't change the form state by itself, just in combination with that specific update pattern by forcing the update to run, right?

Yeah, exactly, it's something in between 

```typescript
updateFn(formStateReducer(formState, action))
```

which would update with every state change and `createFormStateReducerWithUpdate` (which is what you want **most** of the time).
