### ISSUE TITLE
how to access FormState stored as entity (@ngrx/entity)

### ISSUE THREAD

**Issue by Dodobibi** [MrWolfZ/ngrx-forms#129]
In [Getting Started](https://ngrx-forms.readthedocs.io/en/master/user-guide/#getting-started), you update the state in reducer with 
```
const myForm = formGroupReducer(state.myForm, action);
  if (myForm !== state.myForm) {
    state = { ...state, myForm };
  }
```
But when using @ngrx/entity, the state gived to reducer is like this : 
```
{
    entities: {
        "form_id": FormState,
        "other_form_id": OtherFormState,
    },
    ids: [
        "form_id",
        "other_form_id"
    ]
 }
```
 FormState is stored in `entities `object.
 We cannot retrieve the formState with state.xxx or state[xxx] since the action not contains the id of the changed FormState...

with @ngrx/entity, I access the substate with adapter `modelAdapter = createEntityAdapter<FormGroupState<Model>>`

I'm look at #112 but this don't help me...

I want to do this in reducer : **with replacing `state.ids[0]` by the id of the FormState' updated**
```
    const myForm = formGroupReducer(state.entities[state.ids[0]], action);
    if (myForm !== state.entities[state.ids[0]]) {
      state = modelAdapter.updateOne({id: state.ids[0], changes: myForm}, state);
    }
```
Can forms-ngrx be used with @ngrx/entity ?
If yes, how to manage the retrieve id of the FormState?

**Comment by MrWolfZ** [comment]
Sorry for the late response. I don't think it makes sense to store forms with @ngrx/entity since they are not entities. Entities are your business objects/models. The forms are more view models.

That being said I have no practical experience with @ngrx/entity, so it may be possible to do it but I can't help you with it :(

**Comment by MrWolfZ** [comment]
Closed due to inactivity.
