### ISSUE TITLE
boxing undefined value results into an error when creating a form

### ISSUE THREAD

**Issue by dzonatan** [MrWolfZ/ngrx-forms#131]
When creating a form with boxed `undefined` value:
```
let myObject: MyObject; // myObject = undefined
createFormGroupState<MyFormValue>(FORM_ID, {
  someValue: box(myObject),
});
```
The following error is thrown:
` A form control value must be serializable (i.e. value === JSON.parse(JSON.stringify(value))), got: {"__boxed":""}`.

Is this intentional? Can `undefined` be treated the same as `null`?

At the moment current workaround is (in case you do not control the object creation):
```
createFormGroupState<MyFormValue>(FORM_ID, {
  someValue: box(myObject || null),
});
```

**Comment by MrWolfZ** [comment]
Thank you very much for reporting this bug. I have just release version 4.0.1 which contains a fix.
