### ISSUE TITLE
angular material select with multiple option fails

### ISSUE THREAD

**Issue by MadMonkey87** [MrWolfZ/ngrx-forms#132]
Hi,

 

I am using angular material and more specific the mat-select control. For regular mat-select controlls everything works fine using the provided NgrxMatSelectViewAdapter. If I turn the form value into a string array and apply the multiple option on the controll this seems to break the NgrxMatSelectViewAdapter. Choosing a value in the select controll will throw an "value.map is not a function" exception.

 

I guess I need to adapt the NgrxMatSelectViewAdapter for array values but I don't know where to start. any hints on this?

**Comment by MrWolfZ** [comment]
What version are you using? For me the adapter works just fine for a multi select. Have you boxed the value when creating the form state?

**Comment by MadMonkey87** [comment]
Ah I missed the boxing! I also needed to switch the type from string[] | undefined to a string[] only. Anyways, it is working now, thx!
