### ISSUE TITLE
shortcut this library with json schema

### ISSUE THREAD

**Issue by Mojo1** [MrWolfZ/ngrx-forms#134]
Great work,

my feature request is to shortcut the module with https://json-schema.org/ as there are no stable libraries for angular 

this one is not that reliable 
https://www.npmjs.com/package/angular6-json-schema-form
and this one just not ready:
https://jsonforms.io/

**Comment by MrWolfZ** [comment]
Hmm, those libraries do something a bit different from what ngrx-forms is doing. They all render the complete form. ngrx-forms is only doing state management. While it is possible to create a form state based on JSON schema, I am not sure how valuable that would be. In any case, I don't think I will have the time to work on this. Feel free to submit a PR or post some more concrete design thoughts.

**Comment by Mojo1** [comment]
Yes, your are right they work different. Was just an idea which popped up in my head. 
I just thought about the validation - so my main aim to introduce json-schema was to have a powerful possibility to validate objects from one source of truth. 
Also there are validators like https://github.com/epoberezkin/ajv which validate against json schema.
So in my case if i use json-schema and ngrx-forms there would be two sources truth in terms of validation. Anyway i close the issue. I am gonna think about this and come back in case.
Thanks for quick reply

**Comment by Mojo1** [comment]
I'd just wanted to tell you that i did it in the meantime. I auto generate a ngrx-forms state based on a json schema and after this ngrx-forms state is generated I auto generate a form based on an component collection and a second scheme. This form than is auto hooked up to the ngrx-forms state. ajv validator is hooked up as well so it live validates the form fields based on the json schema. I wrote the code for my current employee to i can't share it. It's a great approach so far - opens a lot of possibilities.
