### ISSUE TITLE
How to add validation to groupOptions and to new dynamic group? I have a similar use case as Dynamic form but couldn't find a way to add validations to the  group. 

### ISSUE THREAD

**Issue by fellsquare** [MrWolfZ/ngrx-forms#135]

**Comment by MrWolfZ** [comment]
I'm not sure what you mean by `groupOptions`. But to validate a dynamic form you can use `updateGroup` inside a custom update function to first find the keys of all child controls of a group and build the update function based on those. So for example to add validation to the [dynamic form example](https://github.com/MrWolfZ/ngrx-forms/blob/dd557704f5bf99576827ad790a8d4680f40ecb0c/example-app/src/app/dynamic/dynamic.reducer.ts) you can add the following at line 58:

```typescript
  s = updateGroup<FormValue>(s, {
    group: s => {
      const updates = Object.keys(s.controls).reduce((acc, key) => {
        // use any validation you want here
        acc[key] = validate(required);
        return acc;
      }, {} as StateUpdateFns<FormValue['group']>);
      return updateGroup(s, updates);
    },
  });
```

Please keep in mind that If you want newly added controls to also be validated immediately you need to validate the control when adding it or validate the whole form after the control has been added.

**Comment by fellsquare** [comment]
Thanks for your response. I was able to get the validations working in the dynamic reducer example. I have a requirement where the control inside group has an interface.
```
export interface IGroup {
  line1: string
};

export interface FormValue {
  array: boolean[];
  group: { [id: string]: IGroup };
}
export const INITIAL_STATE = createFormGroupState<FormValue>(FORM_ID, {
  array: [false, false],
  group: {
    abc: {
      line1: ''
    },
    xyz: {
      line1: ''
    },
  },
});
```
I am trying to get the validations to the line1 field following ur example but couldn't get it working. Could you please help?

**Comment by fellsquare** [comment]
Got it working. Thanks.
