### ISSUE TITLE
Question/Feature Request: how can we read the validators (mostly the "required" one) out of the store?

### ISSUE THREAD

**Issue by merobal** [MrWolfZ/ngrx-forms#136]
We have a large project with the requirement of displaying a star (*) if the field is mandatory.

Since we would like to set the validations only in the reducer (including the "required" one), we would like to read this setting from the store. But currently it's returned if there is validation error.

We designed an own solution to read the errors on the initial state and cache that, but we faced that in some cases the initial state is filled, so there is no "required" validation error, but we still need to display the star.

Is there any option to read the validations from the store, or could you introduce a new "validations" object next to the "errors"?

**Comment by MrWolfZ** [comment]
Hmm, I understand your requirement. However, all the options I can think of to solve this in the way you suggest (with a "validations" property on the state) seem quite invasive and would most likely be a breaking change. However, you can do this yourself easily with the help of user defined properties.

This is how you could do it for the `userName` property of the [sync validation example](https://github.com/MrWolfZ/ngrx-forms/blob/dd557704f5bf99576827ad790a8d4680f40ecb0c/example-app/src/app/sync-validation/sync-validation.reducer.ts) in the example app (I haven't tested or compiled the code, but it should give you an idea of how this could work):

```typescript
export const validateAndUpdateForm = updateGroup<FormValue>({
  userName: s => setUserDefinedProperty(validate(s, required), "isRequired", true),
  // + other validations
});
```

Then in the HTML just check `state.userDefinedProperties.isRequired`.

**Comment by tashoecraft** [comment]
This is how I'm accomplishing this but for the opposite use case (showing "optional" for non-required questions).

**Comment by MrWolfZ** [comment]
@merobal were you able to achieve what you want with my suggestion?

**Comment by merobal** [comment]
@MrWolfZ yes, thank you! (We designed a little helper fn to achieve this functionality and works good.)
