### ISSUE TITLE
Access ancestor control when updating group inside array

### ISSUE THREAD

**Issue by Toskv** [MrWolfZ/ngrx-forms#138]
I might just be getting stuck in the typings but I can't find a way to access an ancestor (other than the immediate parent) when when updating a group inside an array.

Consider this:
```typescript
interface Hoove {
  color: string;
}
interface Tail {
  length: number
}
interface Cow {
  hooves: Hoove[];
  tail: Tail;
}
interface Stall {
  cows: Cow[];
  width: number;
}
interface Barn {
  stalls: Stall[];
}

const barnUpdate = updateGroup<Barn>({
  stalls: updateArray<Stall>(updateGroup<Stall>({
    cows: updateArray<Cow>(updateGroup<Cow>({
      hooves: updateArray<Hoove>(updateGroup<Hoove>({
        color: (hoove, cow) => {
          // need stall here
          return hoove;
        }
      }))
    }))
  }))
})


```

When a hoove color is changed I'd like to update the cow.tail as well, but to do that I need the length of the stall it's in.

Is there a way to access it inside the color update function? 
Thanks

**Comment by MrWolfZ** [comment]
Hi, this is easily achieved by using the "uncurried" version of `updateGroup` by making the stall state parameter explicit. So the solution is this:

```typescript
const barnUpdate = updateGroup<Barn>({
  stalls: updateArray<Stall>(stall => updateGroup(stall, { // only change is in this line
    cows: updateArray<Cow>(updateGroup<Cow>({
      hooves: updateArray<Hoove>(updateGroup<Hoove>({
        color: (hoove, cow) => {
          // need stall here
          return hoove;
        }
      }))
    }))
  }))
})
```

**Comment by MrWolfZ** [comment]
@Toskv did this solve your problem? If so, please close this issue.

**Comment by Toskv** [comment]
Hey, it's exactly what I was looking for.

Thanks
