### ISSUE TITLE
Does this work with lazy loaded modules?

### ISSUE THREAD

**Issue by philjones88** [MrWolfZ/ngrx-forms#14]
I have an Angular 5 + NGRX v4.x app that uses lazy loaded module + the per feature store states.

I can't get it working as it keeps throwing the error `The form state must not be undefined!`.

Does ngrx-forms work with this combination?

**Comment by nihique** [comment]
I am doing same and works fine. Can you post snippet of your reducer? Please make sure you are creating default ngrx-form state in your initial reducer state.

**Comment by philjones88** [comment]
reducer:
```export const initialState = createFormGroupState<TemplateViewModel>(
    'cospace-template',
    new TemplateViewModel()
);

export function reducer(state = initialState, action: editTemplateActions.Actions): FormGroupState<TemplateViewModel> {
    switch (action.type) {

        case editTemplateActions.FETCH_COMPLETE:
            return createFormGroupState<TemplateViewModel>(
                'cospace-template',
                action.payload
            );

        default:
            return state;
    }
}```

```
export interface State {
    templates: TemplateListViewModel[];
    meta: TemplateMetaViewModel;
    template: FormGroupState<TemplateViewModel>;
}

export const reducers = {
    templates: fromList.reducer,
    meta: fromMeta.reducer,
    template: fromEdit.reducer
};

export const getTemplateState = createFeatureSelector<State>('cospace-template');

export const getTemplates = createSelector(getTemplateState, (state) => state.templates);
export const getMeta = createSelector(getTemplateState, (store) => store.meta);
export const getTemplate = createSelector(getTemplateState, (store) => store.template);```

**Comment by nihique** [comment]
how did you defined your `initialState` const?

**Comment by philjones88** [comment]
sorry, MD formatting issue. updated snippets

**Comment by philjones88** [comment]
and inside the component:

```
import { Component } from '@angular/core';
import { Observable } from 'rxjs/Observable';
import { Store } from '@ngrx/store';
import { FormGroupState } from 'ngrx-forms';
import * as templateState from '../../reducers';
import * as editTemplateActions from '../../actions/edit';

export class EditComponent {

    public template$: Observable<FormGroupState<AcanoTemplateViewModel>>;
    public meta$: Observable<AcanoTemplateMetaViewModel>;

    constructor(private store: Store<templateState.State>) { }

    public ngOnInit(): void {
        this.template$ = this.store.select(templateState.getTemplate).distinctUntilChanged();
        this.meta$ = this.store.select(templateState.getMeta).distinctUntilChanged();
    }

....
}
```

**Comment by nihique** [comment]
Initial setup looks fine... Are you getting error on initial load or when `FETCH_COMPLETE` action finishes? Make sure payload has data. Also, can you post `TemplateViewModel` definition? Btw, you are missing ngrx-form action processing, see `formGroupReducer()` usage from docs...

```typescript
export function appReducer(state = initialState, action: Action): AppState {
  const myForm = formGroupReducer(state.myForm, action);
  if (myForm !== state.myForm) {
    state = { ...state, myForm };
  }

  switch (action.type) {
    case 'some action type':
      // modify state
      return state;

    default: {
      return state;
    }
  }
}```

**Comment by philjones88** [comment]
If I comment out the dispatch for `FETCH` (effect then does a http get and dispatches `FETCH_COMPLETE` with the model) it still happens.

I've added the `formGroupReducer()` to no effect like so:

```
export const initialState = createFormGroupState<TemplateViewModel>(
    'template',
    new TemplateViewModel()
);

export function reducer(state = initialState, action: editTemplateActions.Actions): FormGroupState<TemplateViewModel> {
    const myForm = formGroupReducer(state, action);
    if (myForm !== state) {
        state = { ...state, ...myForm };
    }

    switch (action.type) {

        case editTemplateActions.FETCH_COMPLETE:
            return createFormGroupState<TemplateViewModel>(
                'template',
                action.payload
            );

        default:
            return state;
    }
}
```

The definition of `TemplateViewModel` is rather large. I might try swapping to a smaller class.

I wonder if it's because I do `new TemplateViewModel()` rather than making an object like your examples? (`{ foo: 'bar', bar: 'foo' ... }`)

**Comment by nihique** [comment]
I was thinking same, in my projects I am not using typescript classes for any of NGRX states, only interfaces and regular functions for object default construction (instead of class constructors). I would just make simple interface with one or two properties and getting that running, and only then, I would start enhancing model slowly with your expected ViewModel's data...

**Comment by philjones88** [comment]
Swapped to:
```
export class TemplateViewModelSimple {
    public name: string;
    public description: string;
}
```

and 

```
export const initialState = createFormGroupState<TemplateViewModelSimple>(
    'template',
    {
        name: '',
        description: ''
    } as TemplateViewModelSimple
);
```

and still the error.

**Comment by philjones88** [comment]
Ah god. I've got it, I had a copy paste issue:

```
<form #templateForm="ngForm" novalidate class="horizontal-form" [ngrxFormState]="(formState$ | async)">
```

rather than:

```
<form #templateForm="ngForm" novalidate class="horizontal-form" [ngrxFormState]="(template$ | async)">
```

D'oh.

**Comment by nihique** [comment]
nice ;) was not expecting issue there ;)

**Comment by MrWolfZ** [comment]
@nihique thanks for helping out on this

@philjones88 to catch these issues earlier in the future you can use ahead-of-time compilation which will also check your templates to see if you are referencing any invalid variables. If you are using Visual Studio Code you can also use the Angular Language Service extension that will highlight such issues already when writing the code.
