### ISSUE TITLE
Not compatible with Typescript 3.4

### ISSUE THREAD

**Issue by jacqui932** [MrWolfZ/ngrx-forms#142]
Hi,

Thanks for writing such a fantastic library.  However, it looks like the latest code (I'm using 4.0.1) is not compatible with Tyepscript 3.4 onwards.

I am getting the following errors on startup:

ERROR in node_modules/ngrx-forms/src/boxing.d.ts(5,18): error TS2430: Interface 'UnboxedArray<T>' incorrectly extends interface 'T[]'.
  Index signatures are incompatible.
    Type 'Unboxed<T>' is not assignable to type 'T'.
      Type 'T extends Boxed<symbol> ? any : T extends Boxed<undefined> ? undefined : T extends Boxed<null> ? null : T extends Boxed<string> ? string : T extends Boxed<string> ? string : T extends Boxed<string> ? string : T extends Boxed<string> ? string : T extends Boxed<number> ? number : T extends Boxed<...> ? number : T exte...' is not assignable to type 'T'.
        Type 'T extends Boxed<undefined> ? undefined : T extends Boxed<null> ? null : T extends Boxed<string> ? string : T extends Boxed<string> ? string : T extends Boxed<string> ? string : T extends Boxed<string> ? string : T extends Boxed<number> ? number : T extends Boxed<number> ? number : T extends Boxed<...> ? number : T e...' is not assignable to type 'T'.
          Type 'T extends Boxed<null> ? null : T extends Boxed<string> ? string : T extends Boxed<string> ? string : T extends Boxed<string> ? string : T extends Boxed<string> ? string : T extends Boxed<number> ? number : T extends Boxed<number> ? number : T extends Boxed<number> ? number : T extends Boxed<...> ? number : T extends...' is not assignable to type 'T'.
            Type 'T extends Boxed<string> ? string : T extends Boxed<string> ? string : T extends Boxed<string> ? string : T extends Boxed<string> ? string : T extends Boxed<number> ? number : T extends Boxed<number> ? number : T extends Boxed<number> ? number : T extends Boxed<number> ? number : T extends Boxed<...> ? boolean : T ex...' is not assignable to type 'T'.
              Type 'string | (T extends Boxed<string> ? string : T extends Boxed<string> ? string : T extends Boxed<string> ? string : T extends Boxed<number> ? number : T extends Boxed<number> ? number : T extends Boxed<number> ? number : T extends Boxed<number> ? number : T extends Boxed<...> ? boolean : T extends Boxed<...> ? boolea...' is not assignable to type 'T'.
                Type 'string' is not assignable to type 'T'.

**Comment by MrWolfZ** [comment]
Thanks for making me aware of this. I'll push out a new major version that is compatible with TS 3.4.0, but it may take me until the weekend.

**Comment by jacqui932** [comment]
No problem.  This is not a problem for me at the moment since I can use an older version of Typescript with Angular 7 but I it looks like Angular 8 depends on later versions of Typescript.

**Comment by MrWolfZ** [comment]
Just to give those interested an update. I have looked into compatibility with 3.4 and the issue pointed out above is easy to fix. However, there are sadly some other issues with the recursive types for `Unboxed` and `FormState`, due to 3.4. giving an error for deeply nested recursive types. I am not sure yet how to solve those, so it may take some time.

**Comment by jacqui932** [comment]
Hi - thanks for the update.  Sorry for being such a pain by bringing this one up :-(

**Comment by MrWolfZ** [comment]
Alright, I was able to resolve the issues. I'll release a new major version as soon as Angular 8 comes out. Since I am not so actively monitoring the Angular release cycles anymore, it would be great if someone could ping me here once its out, otherwise the update may be a bit late.

**Comment by magnattic** [comment]
Maybe you could release a prerelease version (something like 5.0.0-rc.0) for the folks that want to test ng v8? This way we could use your solution already and notice any problems early.

**Comment by MrWolfZ** [comment]
Alright, I have published v5.0.0-beta.1 that supports Angular 8 and TypeScript 3.4.X. You can get it via

```
npm install ngrx-forms@next --save
```

I'll close this issue for now. If you encounter any problems with the beta release, please create new issues.

**Comment by magnattic** [comment]
@MrWolfZ Angular 8 is out now: https://github.com/angular/angular/blob/master/CHANGELOG.md

**Comment by nihique** [comment]
@MrWolfZ Thank you, we just upgraded to Angular 8 and ngrx-forms 5.0.0-beta1 works great

**Comment by MrWolfZ** [comment]
Alright, I'll release v5.0.0 on the weekend. Until then it should be perfectly safe to use the beta, since I will not be making any code changes for the official release anyways.
