### ISSUE TITLE
disable control without clearing validators

### ISSUE THREAD

**Issue by magnattic** [MrWolfZ/ngrx-forms#144]
Right now if you disable a control it automatically becomes valid. It would be awesome to be able to disable a control and still keep its validators and errors in place.

My use case:

I have a text input for "zip code" and dropdown for "city". Both are required. One zip code may belong to multiple cities.

If you input a zip code, it is checked by an async validator and if there is exactly one city, the value is set automatically and the city input becomes disabled.
If there are multiple cities, the user has to choose from a dropdown which city is correct.

This is what happens right now:
1. zip input is empty -> city dropdown is empty and disabled (therfore valid!)
2. zip input is not empty -> becomes valid
3. async validator triggers -> gets isValidationPending
4. async validator completes -> city dropdown is enabled and becomes invalid

At step 2 the form becomes valid even though it shouldn't. SET_VALUE sets a value in the zip input, making it valid and only then the effect for the async validator sets the isValidationPending.

So for a short moment, the form becomes valid before async validation sets in. This leads to problems if I have effects checking if the form is valid.

How do I solve this?

One solution I see is keeping the city dropdown invalid even if it is disabled. Would this be possible? What other options do I have to not have a valid form state before the async validator sets in?

Another option I can think of is starting the async validation process in the reducer, right away when the zip value changes, but there is no method for this, only actions...

**Comment by MrWolfZ** [comment]
Your second idea could work, i.e. start the validation inside the reducer when the zip value changes. There are indeed no update functions for the async validation stuff (I may add those in the future, but I'd happily take a PR for this), but you can always do the same with actions.

So, in your reducer, where you may want to do this:

```ts
const updatedForm = updateGroup<MyForm>(form, {
  city: startAsyncValidation('cityExists'), // the startAsyncValidation function doesn't exist
})
```

you can just do this:

```ts
const updatedForm = formStateReducer(form, new StartAsyncValidationAction(form.controls.city.id, 'cityExists'))
```

**Comment by MrWolfZ** [comment]
@magnattic did my suggestion help you solve your issue?

**Comment by magnattic** [comment]
I used another workaround but plan on refactoring this later to your suggested solution. That should definitely work, so I guess we can close this issue, thanks!

I think it would be awesome to have methods for
-startAsyncValidation()
-clearAsyncError()
-setAsyncError()
to be more flexible and able to use custom Actions for some things.

I'm happy to open a PR, just need some time. :)
