### ISSUE TITLE
Managing state of repeated form inside component 

### ISSUE THREAD

**Issue by rc201612** [MrWolfZ/ngrx-forms#145]
Hi, 

Is it possible to manage the state of many identical forms through an array from the store? 

Basically I have a number of cards that I display using an ngFor and I want each card to contain its own form and save button.

Is there an example of this floating around anywhere? 

Any help very much appreciated. 

Thanks.

**Comment by MrWolfZ** [comment]
Hi. Yes, this is easily possible. This [code sandbox](https://codesandbox.io/s/5z81nxp294) shows how you can do this.

**Comment by rc201612** [comment]
Hi. 

Thanks. That's a great help. 

Do you have an example for putting a save button in each card and controlling whether it is enabled or disabled based on the two text boxes both having values for each card? 

Thanks.

**Comment by MrWolfZ** [comment]
Sure, I have adjusted [the sandbox](https://codesandbox.io/s/rr9w8wnq84) to contain a submit button for each card.
