### ISSUE TITLE
Cannot enable array state if it contains no items

### ISSUE THREAD

**Issue by nihique** [MrWolfZ/ngrx-forms#149]
Hello @MrWolfZ ,

Thanks for library, it is core of our app.  Yesterday we have upgraded from ngrx-forms version 2.3.6 to latest 5.0.0-beta1 and we face breaking change (and I would even say it is bug). We cannot enable previously disabled array state if it has no items. See reproduction in code sandbox below.

https://codesandbox.io/s/ngrxforms-base-vl5bg

I tried to find issue and end up in this piece of code in `enabledReducer$()`, where it is returning unchanged state. I think it is wrong check, it should be similar to what `disableReducer$()` is doing. 

![image](https://user-images.githubusercontent.com/349259/58626865-121ccb80-82d6-11e9-8639-e9da009327cb.png)

Is this bug and is there some easy workaround?

**Comment by MrWolfZ** [comment]
Thanks for the bug report. I have released a [new beta](https://github.com/MrWolfZ/ngrx-forms/releases/tag/v5.0.0-beta.2) which contains a fix. You can get it via `npm i ngrx-forms@next -S`.

**Comment by nihique** [comment]
Thanks, Speedy Gonzales ;)
