### ISSUE TITLE
ngrx-forms for angular 8 and typescript 3.4.5

### ISSUE THREAD

**Issue by dawinter** [MrWolfZ/ngrx-forms#151]
Hello, after upgrading to angular 8 I get the following error. Can you provide a angular 8 compatible version?

ERROR in node_modules/ngrx-forms/src/boxing.d.ts(5,18): error TS2430: Interface 'UnboxedArray<T>' incorrectly extends interface 'T[]'.
  Index signatures are incompatible.
    Type 'Unboxed<T>' is not assignable to type 'T'.
      Type 'T extends Boxed<symbol> ? any : T extends Boxed<undefined> ? undefined : T extends Boxed<null> ? null : T extends Boxed<string> ? string : T extends Boxed<string> ? string : T extends Boxed<string> ? string : T extends Boxed<string> ? string : T extends Boxed<number> ? number : T extends Boxed<...> ? number : T exte...' is not assignable to type 'T'.
        Type 'T extends Boxed<undefined> ? undefined : T extends Boxed<null> ? null : T extends Boxed<string> ? string : T extends Boxed<string> ? string : T extends Boxed<string> ? string : T extends Boxed<string> ? string : T extends Boxed<number> ? number : T extends Boxed<number> ? number : T extends Boxed<...> ? number : T e...' is not assignable to type 'T'.
          Type 'T extends Boxed<null> ? null : T extends Boxed<string> ? string : T extends Boxed<string> ? string : T extends Boxed<string> ? string : T extends Boxed<string> ? string : T extends Boxed<number> ? number : T extends Boxed<number> ? number : T extends Boxed<number> ? number : T extends Boxed<...> ? number : T extends...' is not assignable to type 'T'.
            Type 'T extends Boxed<string> ? string : T extends Boxed<string> ? string : T extends Boxed<string> ? string : T extends Boxed<string> ? string : T extends Boxed<number> ? number : T extends Boxed<number> ? number : T extends Boxed<number> ? number : T extends Boxed<number> ? number : T extends Boxed<...> ? boolean : T ex...' is not assignable to type 'T'.
              Type 'string | (T extends Boxed<string> ? string : T extends Boxed<string> ? string : T extends Boxed<string> ? string : T extends Boxed<number> ? number : T extends Boxed<number> ? number : T extends Boxed<number> ? number : T extends Boxed<number> ? number : T extends Boxed<...> ? boolean : T extends Boxed<...> ? boolea...' is not assignable to type 'T'.
                Type 'string' is not assignable to type 'T'.

**Comment by MrWolfZ** [comment]
There already is a version compatible with Angular 8, but is in beta. You can get it via

npm install ngrx-forms@next --save

It should be safe to use. I will release the full version on the weekend.

**Comment by dawinter** [comment]
Great Thanks. Yes the next version fix the issue.
