### ISSUE TITLE
I can't focus on ion-input

### ISSUE THREAD

**Issue by orochies** [MrWolfZ/ngrx-forms#159]
I am using ionic v4 and angular v8.

I want to put the focus on ion-input text after an action is launched, but this does not work, the code I have is as follows:

`@Effect()
  productAdd$ = this.actions$
    .pipe(
     ofType(PRODUCT_ADD, PRODUCT_EDIT),
      map(() => {
        return new FocusAction('product-form.name');
      })
    );`

 in the template:

`<ion-input type="text" [ngrxFormControlState]="(formState$ | async).controls.name" [ngrxEnableFocusTracking]="true">
    </ion-input>`

But only validation fire and the ion-input not be focused. Thanks.

**Comment by MrWolfZ** [comment]
My apologies for never replying. I hope you have solved this yourself by now. Feel free to open a new issue if you are still facing problems.
