### ISSUE TITLE
Example app layout doesn't fit 1280px screen width

### ISSUE THREAD

**Issue by dskopa-softdev** [MrWolfZ/ngrx-forms#16]
![](https://i.imgur.com/58PCtkK.png)

even if i can scroll to the right to see full json panel, there is no way to see what is hidden under the nav panel on the left

**Comment by MrWolfZ** [comment]
And that is why I hate CSS. And flexbox is sadly not the silver bullet it promises to be. I pushed a new version that fixes the layout issue. Thanks for pointing this issue out to me.
