### ISSUE TITLE
Submit firing on forms after upgrade

### ISSUE THREAD

**Issue by Drammy** [MrWolfZ/ngrx-forms#162]
Hi,

I'm having an issue where forms using ngrx-forms to store state in the reducer are firing submit() after an upgrade to 5.2.1.

Any ideas?
(apologies if this is a little vague - I'm not at my machine right now but thought I'd ask the question in the hope I get a response before I am able to provide more info)

**Comment by MrWolfZ** [comment]
No, I don't really have any ideas sadly. **ngrx-forms** does not do any form submitting. The only thing it does is to intercept form submits (if you use the `ngrxFormState` directive on a `<form>` element) and prevent their default. So I don't see any reason why your form would suddenly start submitting after the upgrade.

**Comment by Drammy** [comment]
Will close this - looks like its some third party component
