### ISSUE TITLE
question: Using formarraystate

### ISSUE THREAD

**Issue by nuaamns** [MrWolfZ/ngrx-forms#167]
This ngrx-forms is really what I needed, and I have some questions about the formarraystate.
in my situation, I should store formarray, formgroup and other texts,like:
// model
```
class Book {
  id: number;
  active: boolean;
  name: string;
}

class Filter {
  name: string;
  isActive: boolean;
}
```

// without ngrx-forms
```
export interface State {
  results: Book[];             // should be formarray if use form
  filter: Filter;                  // should be formgroup if use form
  selectedId;
}
```

// with ngrx-forms, I tried this
```
export interface State {
  resArray: FormArrayState<Book>;
  filterGroup: FormGroupState<Filter>;
  selectedId:  number;
}
```

But it seems not working to me. in this case,  the resArray should be an array of formgroup, but actually it is an array of formcontrol, that seems not right.
if do `let control of resArray`, the control is formcontrol type, But it should be a formgrou like this
```
this.formBuilder.group({
  id: [],
  name: [''],
  active: []
});
```
This is really confuse me, pls help

**Comment by MrWolfZ** [comment]
Which version of **ngrx-forms** and TypeScript are you using? For me locally with latest **ngrx-forms** and TS 3.4.5 the controls of `resArray` are correctly inferred to be form groups.

**Comment by nuaamns** [comment]
ngrx-forms 4.0, typescript 3.2, I'm using formarray in a editable table

**Comment by MrWolfZ** [comment]
hmm, I have created an app with **ngrx-forms** 4.0.1 and TypeScript 3.2.4 with the code below. Both `y` and `control` are properly inferred to be of type `FormGroupState<Book>`. Can you create a reproduction app or post some more code (i.e. the specific code where compilation fails due to the wrong type)?

```ts
class Book {
  id: number;
  active: boolean;
  name: string;
}

class Filter {
  name: string;
  isActive: boolean;
}

export interface State {
  results: Book[]; // should be formarray if use form
  filter: Filter; // should be formgroup if use form
  selectedId: number;
}

export interface State2 {
  resArray: FormArrayState<Book>;
  filterGroup: FormGroupState<Filter>;
  selectedId: number;
}

export function f() {
  let x: State2 = undefined!;

  let y = x.resArray.controls[0];
  console.log(y);

  for (let control of x.resArray.controls) {
    console.log(control);
  }
}
```
