### ISSUE TITLE
Using broader state in validations

### ISSUE THREAD

**Issue by tjlittle** [MrWolfZ/ngrx-forms#170]
Hello @MrWolfZ,

Thanks for creating ngrx-forms. My team and I have found it very useful. We have one nagging issue though. We're probably just missing something, but so far we haven't found a solution we like.

Our application has very complicated validations - it's not uncommon for us to include a significant portion of our state in a validation for a single field. 

If I'm understanding this section of code correctly, we have access to the control state and the form state through the state update functions, but the library doesn't support passing the entire ngrx feature state.

`
export type StateUpdateFns<TValue extends KeyValue> = {
  [controlId in keyof TValue]?: ProjectFn2<FormState<TValue[controlId]>, FormGroupState<TValue>>;
};
`

Is that correct?

Right now, to get access to broader state in validations, we choose an arbitrary form control, and set user defined properties on it with all the other state we need for our validations. However, it's messy, and leads to sync issues within our ngrx state as we copy data items from their "true place" in our data store to places where we can access them for validation. It's a very heavy and bug-ridden process.

Is there a better way?

I've seen that you can [manage the form state reducer locally](https://ngrx-forms.readthedocs.io/en/master/user-guide/local-form-state/). This may be a solution - I just noticed it while I was writing this question, so I haven't really had time to evaluate it.

**Comment by MrWolfZ** [comment]
There are two approaches that I usually suggest. The first is using user defined properties as you are already doing. As you mention, this doesn't scale nicely. The second approach is to simply pass your feature state (which I assume contains your form state) to the update function like this:

```ts
interface MyFormValue {
  someStringWithRequiredMinLength: string
}

interface FeatureState {
  formState: FormGroupState<MyFormValue>
  minLengthForFieldInForm: number
}

// alternatively you can also just pass in the data from the
// feature state you need for your validations
const validateFormState = (featureState: FeatureState) => 
  updateGroup<MyFormValue>({
    someStringWithRequiredMinLength: validate(
      minLength(featureState.minLengthForFieldInForm)
    )
  })

function featureReducer(featureState: FeatureState, action: Action) {
  let updatedFormState = formStateReducer(featureState.formState, action)
  updatedFormState = validateFormState(featureState)(updatedFormState)

  if (updatedFormState !== featureState.formState) {
    featureState = { ...featureState, formState: updatedFormState }
  }

  // reduce other actions

  return featureState
}
```

I hope this points you in the right direction.

**Comment by tjlittle** [comment]
@MrWolfZ - wow. When you write it out like that, it seems blindingly obvious. Not sure how we missed it for so long. Thanks for the help!
