### ISSUE TITLE
SetAsyncErrorAction fails when setting error object for second time

### ISSUE THREAD

**Issue by boristomic** [MrWolfZ/ngrx-forms#175]
I'm call endpoint from effect to do some validations, call looks like this.

```
return this.service.validate()
    .pipe(
    map((response): Action => {
        if (response.hasError) {
        return new SetAsyncErrorAction(FORM_CONTROL, VALIDATION_ID, response.errors)
        }

        return new ClearAsyncErrorAction(FORM_CONTROL, VALIDATION_ID)
    }),
    catchError(error => of(new SetAsyncErrorAction(FORM_CONTROL, VALIDATION_ID, error))),
    startWith(new StartAsyncValidationAction(FORM_CONTROL, VALIDATION_ID))
    )
```

When network connection is lost (in this example) `catchError` is called and error is set with no issues. However if I make another call and receive error `catchError` is called again and app crashes.

![Screenshot 2020-01-28 at 13 48 35](https://user-images.githubusercontent.com/16724532/73266505-4afba000-41d7-11ea-816f-09048715c33b.png)

**Comment by dzonatan** [comment]
Are you intentionally storing your entire failed request "XMLHttpRequest" as error under form control? Seems strange why you need to do that.

If that's needed anyway, then [deepEquals](https://github.com/MrWolfZ/ngrx-forms/blob/cf25f2aa46831b5d315c79d3e1c7397d92d190c9/src/util.ts#L5) function has to be modified to take into account these advanced-access/restricted properties.

**Comment by boristomic** [comment]
There is no actual need for my use case to store entire error object so I have modified it, however it should not crash the app if there is need for it.

**Comment by MrWolfZ** [comment]
Checking for such objects would be rather difficult. The general rule for ngrx is to only use safely serializable objects in actions and the store. Therefore, I won't provide a fix for this.
