### ISSUE TITLE
Dynamic validation

### ISSUE THREAD

**Issue by eras0r** [MrWolfZ/ngrx-forms#177]
Hi,

first of all thanks for creating ngrx-forms. I have a question about dynamic validation.
- I load the user being edited from the REST API (UserActions.loadUserSuccess is being dispatched upon successful retrieval)
- if the loaded user already has an age, the age field within the form is required, otherwise not.

I tried the following:

```ts
export const userFeatureKey = 'user';

export const userEditFormId = 'user.edit.form';

export interface UserState {
    userEditForm: FormGroupState<User>;
    user: User; // holds the user currently being edited (used for dynamic form validation)
}

export function initFormState(): FormGroupState<User> {
    return createFormGroupState<User>(userEditFormId, {});
}

export const initialState: UserState = {
    userEditForm: initFormState(),
    user: null
};

const userReducer = createReducer<UserState>(
    initialState,

    // ngrx forms reducer
    onNgrxForms(),

    on(UserActions.loadUserSuccess, (state, {user}) => {
        console.log('REDUCER'); // gets invoked before the validateAndUpdateForm function
        const newState = {...state};
        newState.user = user;

        newState.userEditForm = createFormGroupState<User>(userEditFormId, user);

        return newState;
    }),
);

const validateAndUpdateForm = (featureState: UserState) => {
    console.log('validateAndUpdateForm, featureState: ', featureState); // does not get invoked after the reducer has been invoked

    return updateGroup<User>({
        age: (state, parentState) => {
            // validation dependent on loaded user within feature state
            if (featureState.user && featureState.user.age) {
                console.info('age required');
                return validate(state, required);
            }

            console.info('age NOT required');
            return validate(state, () => {
                return {};
            });
        }
    });
};

export function reducer(state = initialState, action: Action) {
    return wrapReducerWithFormStateUpdate(
        userReducer,
        s => s.userEditForm,
        validateAndUpdateForm(state)
    )
    (state, action);
}

```

As I commented within the code my userRedcuer gets invoked before the validateAndUpdateForm function (and therefore has with the old state). 
- Am I doing something wrong here? 
- Is there even a better approach to achieve such a dynamic validation?

I noticed, that when I click into the form field and leave it, the blur event will trigger the MARK_AS_TOUCHED action and my validateAndUpdateForm function is getting reinvoked (this time with the proper state).

Thanks

**Comment by dzonatan** [comment]
> As I commented within the code my userRedcuer gets invoked before the validateAndUpdateForm function (and therefore has with the old state)

It works as intended. Not sure what problem you have here. If you want to do something else on `loadUserSuccess` case and need your form to be validated at such moment - just call `validateAndUpdateForm` manually:
```ts
    on(UserActions.loadUserSuccess, (state, {user}) => {
        const newState = {...state, user };

        newState.userEditForm = createFormGroupState<User>(userEditFormId, user);

        newState = validateAndUpdateForm(newState); // here

        return newState;
    }),
```

> I noticed, that when I click into the form field and leave it, the blur event will trigger the MARK_AS_TOUCHED action and my validateAndUpdateForm function is getting reinvoked

This also works as expected.

> Is there even a better approach to achieve such a dynamic validation?

Only one thing comes to my mind: if you do not have any other validators, instead of 
```ts
  validate(state, () => {
    return {};
  })
```
you can use `setErrors(state, {})`.

**Comment by eras0r** [comment]
@dzonatan thanks for your quick response.

> Oh.. I see your issue now. validateAndUpdateForm holds the old value because it's called BEFORE your reducer. Not after. One of the possible solutions is to use userDefinedProperties:

I think this is exactly my issue. The documention of the wrapReducerWithFormStateUpdate function say the following:

> This function wraps a reducer and returns another reducer that first calls the given reducer and then calls the given update function for the form state that is specified by the form state locator function.

why I understood, that the reducer is invoked BEFORE the given validation function. But this seems not to be the case.

I gave you proposed solution (with the user defined properties) a shot and was able to correctly trigger my validation.

However I am still wondering if there is no simpler way to achieve this. As I think the solution is rather complex for such a common use case in larger business applications.

**Comment by dzonatan** [comment]
>>   This function wraps a reducer and returns another reducer that first calls the given reducer and then calls the given update function for the form state that is specified by the form state locator function.

> why I understood, that the reducer is invoked BEFORE the given validation function. But this seems not to be the case.

Actually it does what it declares. [First it calls the given reducer](https://github.com/MrWolfZ/ngrx-forms/blob/d974581cd9694c3e6d5b84b070a3507eaf8ea1eb/src/reducer.ts#L150) and only [then update function](https://github.com/MrWolfZ/ngrx-forms/blob/d974581cd9694c3e6d5b84b070a3507eaf8ea1eb/src/reducer.ts#L155).
Your problem actually has nothing to do with this utility function, rather with functional programming fundamentals.

```ts
wrapReducerWithFormStateUpdate(
  userReducer,
  s => s.userEditForm,
  /**
   * at the time `reducer` was called, the "state" object is passed to `validateAndUpdateForm`
   * which holds no data about a `user` because `userReducer` was not called yet.
   * and because you don't change the value of the same reference in your `userReducer`
   * you always have the "old" state here.
   */
  validateAndUpdateForm(state) 
)
```

Maybe this will give you a better idea what's happening:
```ts
export function reducer(state = initialState, action: Action) {
    const updateFn = validateAndUpdateForm(state); // take attention to this - this is the same as your original reducer
    return wrapReducerWithFormStateUpdate(
        userReducer,
        s => s.userEditForm,
        updateFn,
    )
    (state, action);
}
```

> However I am still wondering if there is no simpler way to achieve this. As I think the solution is rather complex for such a common use case in larger business applications.

Your code contains a lot of noise. Try to take use of projection functions. After quick cleanup it doesn't look that complex for me:
```ts
const userReducer = createReducer<UserState>(
  initialState,
  onNgrxForms(),
  on(UserActions.loadUserSuccess, (state, { user }) => ({
    ...state,
    user,
    userEditForm: setUserDefinedProperty(
      createFormGroupState(userEditFormId, user),
      'required',
      !!user.age
    ),
  }))
);

const validateAndUpdateForm = updateGroup<User>({
  age: (state, parentState) => {
    const validationFns: ValidationFn<string>[] = [pattern(/[0-9.]+/)];

    // add addtional required validation if user already has an age
    if (parentState.userDefinedProperties.required) {
      validationFns.push(required);
    }

    return validate(state, validationFns);
  },
});

export const reducer = wrapReducerWithFormStateUpdate(
  userReducer,
  s => s.userEditForm,
  validateAndUpdateForm
);
```

If you still prefer not to use `userDefinedProperties` but instead keep flags on your root state.
Then instead of `wrapReducerWithFormStateUpdate` just simply wrap your user reducer with `validateAndUpdateForm`:
```ts
export const reducer = (state = initialState, action: Action) =>
  validateAndUpdateForm(userReducer(state, action));
```

**Comment by eras0r** [comment]
Thanks for explaining me my problem behind the wrapReducerWithFormStateUpdate function.
You are completely right, that i misunderstood the concept there. Your explanations and references to the source code were very helpful and made it clear to me, that my validation function is being invoked with the old state and not the modified state by my reducer. 

After you suggestions I ended up with the following code within my userRedcuer.

```ts
const userReducer = createReducer<UserState>(
    initialState,
    onNgrxForms(),
    on(UserActions.loadUserSuccess, (state, { user }) => ({
        ...state,
        user,
        userEditForm: updateGroup<User>({
            age: ctrl => setUserDefinedProperty(ctrl, 'required', !!user.age)
        })(state.userEditForm)
    }))
);
```

Hint: I need the user defined property on the age field not on the form as there are more fields with such user defined validations in my case. 

Is this the easiest way to achieve this in your opinion?

Thanks again
