### ISSUE TITLE
Load Initial data on forms from server

### ISSUE THREAD

**Issue by PedroEsnaola** [MrWolfZ/ngrx-forms#180]
I have a really long form, and in my project, the user must be able to stop filling out the form at any time, and come back later, however, I have not found a way to load the initial state from an API (for example)

**Comment by MrWolfZ** [comment]
You can just create an initialization action which is dispatched inside your effects (or a component/service/whatever) with the data from the API. Then, inside the handler for that action either use `setValue` to update the form value or completely re-initialize the form state by simply calling `createFormGroupState` again.

**Comment by PedroEsnaola** [comment]
i made an action for this, but i dont know how to set the value on form state.
just call setValue? or i need to pass his return to something

**Comment by PedroEsnaola** [comment]
i did it!!
thanks for the help!!
