### ISSUE TITLE
Re-using control components for both local and global state

### ISSUE THREAD

**Issue by Plondrein** [MrWolfZ/ngrx-forms#188]
I've got a control that I want to use sometimes as single form (therefore I use local state as it's dead simple) but sometimes I want to include it in more complex form where i use global state - but i saw that using **ngrxFormsAction** action handler disables global directive - is it uncommon scenario or is just unsupported yet? I resolved this via conditionally bind **ngrxFormsAction** to either dispatch action to store or emit action to parent - but i'm not sure that's the way to go.

Cheers

**Comment by MrWolfZ** [comment]
Yes, what you describe is the way I would go. Internally, the action you get in `(ngrxFormsAction)` is just dispatched on the global action subject if no handler is defined for `ngrxFormsAction`. Therefore, if you have a switch that either emits to the parent or dispatches to the store, that achieves exactly what you want.
