### ISSUE TITLE
Question: Isn't putting `forms` into the `Store` considered as a bad practice?

### ISSUE THREAD

**Issue by ttma1046** [MrWolfZ/ngrx-forms#190]
Quote from Brandon Roberts & Mike Ryan
"What doesn't belong to the 'Store' ?" "Forms!"

from this talk during ng-conf 2018

Reducing the Boilerplate with NgRx - Brandon Roberts & Mike Ryan
https://youtu.be/t3jx0EC-Y3c?t=702

**Comment by ttma1046** [comment]
![image](https://user-images.githubusercontent.com/1035498/83823568-a99dd100-a717-11ea-83cf-81bdb65147bc.png)

**Comment by MrWolfZ** [comment]
I am familiar with their opinion, but I disagree. There are a lot of reasons why you may want to put your forms into the store, e.g. for better debuggability (unfortunately `@angular/forms` is a mutable mess that is really difficult to debug and get right for complex forms), for time travel debugging, for decoupling the lifetime of the form state from the lifetime of the component etc.

That said, for some time now **ngrx-forms** also has support for [local form states](https://ngrx-forms.readthedocs.io/en/master/user-guide/local-form-state/) which allows you to use the functional nature (and resulting benefits) also outside of the store.

But yeah, that is the beauty of open source. Some people may find it useful to put from in the store, others not. For this that do, this library exists. In the project this library originated in I would have gone crazy without it, but even now I tell the devs to not use **ngrx-forms** everywhere, but only where it's capabilities make sense.

**Comment by MrWolfZ** [comment]
Closing the issue since the question was answered.
