### ISSUE TITLE
Component custom validation does not fired

### ISSUE THREAD

**Issue by asnow73** [MrWolfZ/ngrx-forms#191]
Hello! Thanks for lib.

I noticed that component with integrated custom validation does not fired **validate** method, when using ngrx-forms.

Reproduction of the issue in a code sandbox: https://codesandbox.io/s/beautiful-thunder-15ww3?file=/src/app/example/example.component.ts

angular v9.0.0
ngrx-forms v6.3.1

In demo project I have two forms. One form whithout using ngrx-forms, another with using ngrx-forms. Both forms contains "example" component, which has custom validator, validate method (approach described here https://netbasal.com/adding-integrated-validation-to-custom-form-controls-in-angular-dc55e49639ae). 
In first form **validate method is fired**, and in second form (ngrx-forms) **validate method does not fired**. 

Is it bug or feature? May be I do not understand something?

**Comment by dzonatan** [comment]
This works as expected. `ngrx-forms` and native angular forms **validation** has nothing in common. `ngrx-forms` uses value accessor only for syncing value / disabled / touched states but not the validation:
https://ngrx-forms.readthedocs.io/en/master/user-guide/custom-form-elements/

For validation you have to do it on `ngrx-forms` side: https://ngrx-forms.readthedocs.io/en/master/user-guide/validation/

**Comment by asnow73** [comment]
Thanks for answer, @dzonatan 

In this case ngrx-forms restricts the use of this approach for component validation in project with using both kind of forms. To avoid duplication of the validation code, I have to put the validator in a separate function that will be used in native angular form and ngrx-form
