### ISSUE TITLE
help wanted

### ISSUE THREAD

**Issue by smatthaeus** [MrWolfZ/ngrx-forms#194]
[reducer.txt](https://github.com/MrWolfZ/ngrx-forms/files/4827305/reducer.txt)

Hello Jonathan,

I am getting into ngrx-forms and am having some problems. Did not know how else to reach you so I am pinging you on your email. The problem statement is to be able to set the focus on the control field1 which is in the hierarchy. All details in the attachment.

I am not privy to giving all the details. Am attaching the reducer details as an attachment. Any guidance will be helpful. 

The problem I am facing is with the line field1: formStateReducer(control, new FocusAction(control.id)). It says argument of type { field1: FormGroupState<{}> is not assignable to parameter of type StateUpdateFns… 

Thanks in advance. Appreciate all your help.

**Comment by dzonatan** [comment]
You're doing something really wrong here.
Try to use [`focus` and `unfocus` functions](https://ngrx-forms.readthedocs.io/en/master/user-guide/updating-the-state/#focusing-and-unfocusing).

```ts
import { focus } from 'ngrx-forms';

structure1: updateGroup<structure1>({
  field1: focus,
})
```

**Comment by smatthaeus** [comment]
Thanks that worked and appreciate your help very much. Since I was implementing it as part of a reducer i thought a new focus action should be triggered of. I am actually taking small steps here and heavily relying on the examples.  So please  bear with me if i ask stupid questions.. Once again thanks for the turnaround really appreciate it

**Comment by MrWolfZ** [comment]
Thanks @dzonatan for helping.

@smatthaeus no worries, feel free to open a new issue if you have more questions.
