### ISSUE TITLE
Need a code snippet for Dynamic form example

### ISSUE THREAD

**Issue by ahavagowtham** [MrWolfZ/ngrx-forms#208]
I am using ngrx ver-8 and I dont find a code snippet for creating action and reducer for dynamic form control example. In your example you have used the older style of creating action and reducer. It would be great if you can provide an example or code snippet with ngrx v8. Thanks in advance.

**Comment by MrWolfZ** [comment]
The ngrx v8 version would be very similar. Either you dispatch **ngrx-forms** actions like the `AddArrayControlAction` directly and just let `onNgrxForms` do the job or you create your own action and then inside the `on` handler you use functions like `addGroupControl` for update the form state.

**Comment by MrWolfZ** [comment]
Closed due to inactivity. Feel free to open a new issue if you have more questions.
