### ISSUE TITLE
multiple pattern validations on a single control

### ISSUE THREAD

**Issue by bsy** [MrWolfZ/ngrx-forms#209]
Curious how it might be possible to define multiple pattern match validations on a single form control.  I tried to define two, but it looks like only the first one is being triggered in the reducer logic.

**Comment by MrWolfZ** [comment]
Very good point, this is a use-case I did not anticipate or cover. I though about this now but I don't think there is a reasonable way to make it possible to simply use any built-in validator multiple times. However, it is possible to write a `patterns` validator that re-uses the `pattern` validator for this (untested code so be careful):

```ts
import { pattern } from 'ngrx-forms/validation'

export function patterns(patternParams: RegExp[]) {
  const patternValidators = patternParams.map(pattern);

  return <T extends string | Boxed<string> | null | undefined>(value: T): ValidationErrors => {
    const results = patternValidators.map(v => v(value)).filter(r => !!r.pattern)
    return results.length === 0 ? {} : { patterns: results }
  };
}
```

**Comment by MrWolfZ** [comment]
Closed due to inactivity. Feel free to open a new issue if you have more questions.
