### ISSUE TITLE
Use like stepControl on mat-stepper

### ISSUE THREAD

**Issue by aenimaone** [MrWolfZ/ngrx-forms#213]
Great lib. But can I use ngrx-form with mat stepper, maybe I can create adapter FormGroupState to AbstractControlLike or other tric?  Any solutions?

Thanks.

**Comment by MrWolfZ** [comment]
Hmm, not sure if it would work. Looking at the code the component seems to be hard-coded to only work with angular forms. I think the best solution is to simply bind the `completed` property of each step to the form of that step, i.e. `[completed]="firstForm.isValid"`.

**Comment by aenimaone** [comment]
Thanks I will try
