### ISSUE TITLE
Question:  Updating nested group control values based on changes to other control values

### ISSUE THREAD

**Issue by cmdickson** [MrWolfZ/ngrx-forms#231]
I'm new to ngrx-forms, so I'm fairly certain I am missing something obvious here.  I apologize in advance.

Also, if this is not the correct place for questions, again I apologize, just let me know what the preferred process is.

I have a form that is essentially composed of other "sub-forms" and reducer wrapped for updates/validation: 
```
export interface TreatmentFormValue {
    someNumericValue: number;
    someBooleanValue: boolean;
    <lots of other properties>...
}

export interface WorkspaceFormValue {
    treatments: TreatmentFormValue[];
    <other properties>...
}

export interface AppState {
    workspace: WorkspaceFormValue
}

export const mainReducer = createReducer<AppState>(
    initialState,
    onNgrxForms(),
    on(actions.addTreatments, (state, { treatments }) => {
        return {
            ...state,
            workspace: updateGroup<WorkspaceFormValue>(state.workspace, {
                treatments: a => treatments.reduce((prev, curr) => addArrayControl(prev, curr), a)
            })
        };
    })
    ...
);

const updateTreatmentFormState: StateUpdateFns<TreatmentFormValue> = {
    ...
};

const validateTreatmentFormState: StateUpdateFns<TreatmentFormValue> = {
    ...
};

const validateWorkspaceFormState: StateUpdateFns<WorkspaceFormValue> = {
    treatments: treatments => {
        treatments = updateArray(treatments, updateGroup(validateTreatmentFormState));
        return validate(treatments, minLength(1));
    }
};

const updateWorkspaceFormState: StateUpdateFns<WorkspaceFormValue> = {
    treatments: updateArray<TreatmentFormValue>(updateGroup(updateTreatmentFormState))
};

export const validateAndUpdateWorkspaceFormState = updateGroup<WorkspaceFormValue>(updateWorkspaceFormState, validateWorkspaceFormState);

export const testNgrxFormsReducer = wrapReducerWithFormStateUpdate<AppState, FormState<WorkspaceFormValue>>(
    mainReducer,
    s => s.workspace,
    validateAndUpdateWorkspaceFormState
)
```

The `mainReducer` deals with actions to add/remove from the `treatments` array.

I am trying to determine a clean way to implement logic for updating `ActionFormValue` control values based on changes to other values.  For example, if `someBooleanValue` changes, then update `someNumericValue` or vice-versa.  In this case, using `validateAndUpdateWorkspaceFormState` is not applicable (I don't think) as the change/update should only occur when the "trigger" control value actually changes.

Also, since `TreatmentFormValue` is essentially a form on its own, I would like to isolate these rules/state changes from the `mainReducer` if possible (similar to `updateTreatmentFormState`, `validateTreatmentFormState`, above) .

I have investigated creating separate reducers for the "workspace" that invoke a "treatment form" reducer for each, but I think I might be going in the wrong direction.

If you could provide any best practices or suggested approach for this, it would be much appreciated.

Thank you.

**Comment by MrWolfZ** [comment]
Your code looks great and what you are trying to achieve can be done quite easily. Instead of `updateGroup(updateTreatmentFormState)` you can pass a function that takes the control state as an argument. Then you can run your update and afterwards check your rules, like this:

```ts
const updateWorkspaceFormState: StateUpdateFns<WorkspaceFormValue> = {
    treatments: updateArray<TreatmentFormValue>(treatmentControlState => {
        let updatedState = updateGroup(treatmentControlState, updateTreatmentFormState);
        // deal with changes are desired, for example like the following

        // static rule
        if (updatedState.value.someBooleanValue) {
            updatedState = updateGroup(updatedState, {
                someNumericValue: setValue(0),
            });
        }

        // dynamic rule, e.g. compare old and new value
        if (updatedState.value.someNumericValue > treatmentControlState.value.someNumericValue) {
            updatedState = updateGroup(updatedState, {
                someBooleanValue: setValue(false),
            });
        }

        return updatedState;
    }),
};
```

Alternatively you can do this also in `updateTreatmentFormState` (for static rules) by using the second parameter of an update function:

```ts
const updateTreatmentFormState: StateUpdateFns<TreatmentFormValue> = {
  someNumericValue: (state, parentState) => parentState.value.someBooleanValue ? setValue(state, 0) : state,
};
```

**Comment by cmdickson** [comment]
Thanks for the quick response.  

If I understand the code you posted correctly, this works for a scenario where `updateTreatmentFormState` triggers a change to a value that we then check to see if another value should be updated.

This is note quite the scenario I am working on:  In my case, I'm interested in when a value changes due to user input into the form (i.e. `SetValueAction` is dispatched).  So, when the value of a particular form field gets set, then update some other form.

So, I am hoping to have the following happen when a `SetValueAction` is handled:
  1. Appropriate control value updated based on action
  2. Update controls based specifically on "trigger" of the specific control from (1) changing value
  3. Run updates/validation that are independent of specific value change "triggers" (i.e. `validateAndUpdateWorkspaceFormState`)
  
Does that information change your suggested approach, or am I missing something?

Thanks again.

**Comment by MrWolfZ** [comment]
For dynamic rules, you are correct. And there is a way to do it like you describe, but in most situations like yours you can find a way to express the logic as a static declarative rule like the one I outlined above. You just need to change your thinking a bit from an imperative "when action X happens, do Y" to a declarative "value Y depends on value X" mindset (i.e. you don't care about why the value changed, just its current value).

If you could share some more details I could help you in expressing the logic in a declarative way.

However, if you truly need to react to the action/value change, then you'll have to wrap the `mainReducer` with a function that captures the existing value and then compares it with the new value (or checks for the action type).

Alternatively, you could add a second handler for the `SetValueAction` to your `mainReducer`, but I remember there being an issue if you add both `onNgrxForms` and `onNgrxFormsAction` in one reducer. But maybe this has changed since then (I haven't really used Angular or ngrx recently, so I'm not fully up to date with all behavior changes):

```ts
export const mainReducer = createReducer<AppState>(
    initialState,
    onNgrxForms(),
    onNgrxFormsAction(SetValueAction, (state, { controlId }) => {
        if (controlId.startsWith(state.workspace.controls.treatments.id)) {
            // deal with the action ...
        }

        return state
    }),
    on(actions.addTreatments, (state, { treatments }) => {
        return {
            ...state,
            workspace: updateGroup<WorkspaceFormValue>(state.workspace, {
                treatments: a => treatments.reduce((prev, curr) => addArrayControl(prev, curr), a)
            })
        };
    }),
);
```

**Comment by cmdickson** [comment]
> in most situations like yours you can find a way to express the logic as a static declarative rule

Yes, this would definitely be my preference (and one of the main reasons I am refactoring to use your library :) )

I have attempted to write the rule this way, but have not got it working the way it needs to just yet.

I will continue to see if I can get the declarative rule working, and if not you have provided some good alternatives...

Thanks again for your feedback/suggestions
