### ISSUE TITLE
onNgrxForms with ngrx/store 11 returns incompatible types

### ISSUE THREAD

**Issue by bufke** [MrWolfZ/ngrx-forms#232]
**Describe the bug**

When upgrading to ngrx/store 11 the types returned by onNgrxForms are not compatible with other reducers. From the ngrx-forms docs, it's typical to place other reducers after onNgrxForms

```
export const reducer = createReducer(
  initialState,
  onNgrxForms(),

  // your other reducers...
);
```

However this no longer works because the return type of onNgrxForms are all optional but store's on function expects them to be required. We get an error like this:

```
Type '{ newOrganizationForm?: FormGroupState<NewOrganizationFormValue>; }' is not assignable to type '{ newOrganizationForm: FormGroupState<NewOrganizationFormValue>; }'.
  Property 'newOrganizationForm' is optional in type '{ newOrganizationForm?: FormGroupState<NewOrganizationFormValue>; }' but required in type '{ newOrganizationForm: FormGroupState<NewOrganizationFormValue>; }'.ts(2322)
reducer_creator.d.ts(13, 18): The expected type comes from the return type of this signature.
```

A work around is to place onNgrxForms below the other reducers. As long as reducer order doesn't matter.
Another bad work around is to make all reducer state optional.

**To Reproduce**

Here is a simple reducer

```
const initialFormState = createFormGroupState<NewOrganizationFormValue>(
  FORM_ID,
  { name: "" }
);

interface State {
  newOrganizationForm: FormGroupState<NewOrganizationFormValue>;
}

export const initialState: State = {
  newOrganizationForm: initialFormState,
};

export const reducer = createReducer(
  initialState,
  onNgrxForms(),
  on(retrievedOrganizationList, (state, { organizations }) => ({ ...state }))
);
```

**Expected behavior**

This worked when used with ngrx/store 10.x. But not 11.

I would expect the return type of onNgrxForms to not be optional. Given the initial state, it should never be possible for the state types to be optional.

**Library version**:

```
"@ngrx/store": "^11.0.1",
"ngrx-forms": "~6.3.4",
```

**Comment by MrWolfZ** [comment]
I cannot reproduce the issue with the code snippet above. If this issue still exists, please create a new issue and provide a full repository or code sandbox that shows the error.
