### ISSUE TITLE
Which ngrx-forms version would work for Angular 6.1.0 with TypeScript 2.7.2 and NgRx 6.1.2. Upgrade is not possible.

### ISSUE THREAD

**Issue by vegeta03** [MrWolfZ/ngrx-forms#238]
My current project uses Angular 6.1.0 with TypeScript 2.7.2 and NgRx 6.1.2. Upgrade is not possible right now because of big code base and other dependent libraries. There is a serious requirement for the functionality provided by `ngrx-forms`.

Could anyone please provide the compatible `ngrx-forms` version for this issue?

Environment
Angular 6.1.0
TypeScript 2.7.2
NgRx 6.1.2

Thank you.

**Comment by MrWolfZ** [comment]
Unfortunately, I don't believe any version of the library supports such an old TypeScript version. You will have to either upgrade or use a different library.
