### ISSUE TITLE
typing issues when using the ngrxFormControlState directive with potentially boxed values

### ISSUE THREAD

**Issue by anno1985** [MrWolfZ/ngrx-forms#242]
**Describe the bug**
We've got a form state with a property that can hold either a boxed object, or a string, or be undefined:
```
myProp: Boxed<MyObj> | string | undefined,
```

When trying to use that together with the ngrxFormControlState directive as follows:
```
[ngrxFormControlState]="formState.controls.myProp"
```
we get the following type warning:

> Type FormState<MyState["myProp"]> is not assignable to type FormControlState<any> & FormControlState<NgrxFormControlValueType<TStateValue>> & AbstractControlState<any> 

**Expected behavior**
No typing warnings.

**Library version**:
6.3.5

**Additional context**
As a workaround, the following seems to work:
```
myProp: Boxed<MyObj | string> | undefined,
```

**Comment by MrWolfZ** [comment]
I looked into this, and it is incredibly tricky to solve and would likely decrease compilation and IDE performance due to requiring more complex types. Given that there's a workaround and it's a rather rare edge case, I will unfortunately not fix this issue.
