### ISSUE TITLE
Removing a validator on a control leaves behind old validation state

### ISSUE THREAD

**Issue by earyzhe** [MrWolfZ/ngrx-forms#254]
**Describe the bug**
I have a form with a **customer** and **customer location** selection fields.

Some of the customers are Major customers.

Depending on whether the selected customer in the first field is a Major customer I would like to apply a different validator to the form. The reason is, that if the customer is NOT a major customer then the customer location is not required. If the customer is a major customer it is required.

My two validator functions are:
```typescript
/* Major Customer validation for the form */
const validateAndUpdateMajorCustomerFormState =
  updateGroup<ICustomerRebookFormPageValue>({
    customerId: validate(required),
    customerLocationId: validate(required),
    ibcIds: validate(required, minLength(1)),
  });

/* Minor Customer validation for the form */
const validateAndUpdateFormState = updateGroup<ICustomerRebookFormPageValue>({
  customerId: validate(required),
  ibcIds: validate(required, minLength(1)),
});
```

The validator to the form is applied depending on the customer selection
```typescript
  onNgrxFormsAction(SetValueAction, (state, _) => {
    const newForm = state.form;
    const selectedCustomer = state.filteredSelectOptions.customers.data.find(
      (customer) => customer.id === state.form.value.customerId
    );

    return {
      ...state,
      form: selectedCustomer?.isMajorCustomer
        ? validateAndUpdateMajorCustomerFormState(newForm)
        : validateAndUpdateFormState(newForm),
    };
  }),
```

However even after applying the validateAndUpdateFormState validator that does not have the customerLocationId Validator, the customerLocationId validation is still in the form control state and makes in invalid.

![image](https://user-images.githubusercontent.com/26453863/128307091-d833f6e8-5039-4c5f-9592-adff616f5124.png)

My current hack that seems to be working

```typescript
  onNgrxFormsAction(SetValueAction, (state, _) => {
    const newForm = state.form;

    const selectedCustomer = state.filteredSelectOptions.customers.data.find(
      (customer) => customer.id === state.form.value.customerId
    );

    if (selectedCustomer?.isMajorCustomer) {
      return {
        ...state,
        // form: validateAndUpdateFormState(newForm),
        form: validateAndUpdateMajorCustomerFormState(newForm),
      };
    } else {

      return {
        ...state,
        // form: validateAndUpdateFormState(newForm),
        form: validateAndUpdateFormState({
          ...newForm,
          errors: {},
          isInvalid: false,
          isValid: true,
          controls: {
            ...newForm.controls,
            customerLocationId: {
              ...(newForm.controls.customerLocationId as FormControlState<
                number | undefined
              >),
              errors: {},
              isInvalid: false,
              isValid: true,
            },
          },
        }),
      };
    }
  }),
```

**To Reproduce**

1.select a major customer

2.do NOT select a customer location

3.select a minor customer

**Expected behavior**
 The form is validated when the minor customer is selected
observed behavior:  The form is invalid when the minor customer is selected

**Library version**:
6.3.3

**Comment by MrWolfZ** [comment]
Apologies for the late response. You can use the `setErrors` update function to clear any errors for the location ID field for minor customers:

```ts
/* Minor Customer validation for the form */
const validateAndUpdateFormState = updateGroup<ICustomerRebookFormPageValue>({
  customerId: validate(required),
  customerLocationId: setErrors({}),
  ibcIds: validate(required, minLength(1)),
});
```
