### ISSUE TITLE
Ngrx-forms actions replaces whole state rather than updating related properties. 

### ISSUE THREAD

**Issue by AtozEvo** [MrWolfZ/ngrx-forms#259]
Unsure if is a bug or if this is the actual intended outcome. 

**Describe the bug**
When designing a form that holds other information, making the information a property in the form causes it to disappear the moment the form is updated with any `ngrx-forms` actions. I would have expected the actions to update the property of the `FormGroupState` rather than replacing the whole object. 

**To Reproduce**
1. Create Form State
```
export interface StorageboxFormValue {
  index: number;
  name: string;
}

const FORM_ID = 'storage-box-form';
const DEFAULT_FORM_VALUE: StorageboxFormValue = {
  index: 0,
  name: '',
};

const initialState: StorageBoxFormFeatureState = {
  boxId: 'asd',
  ...createFormGroupState(FORM_ID, DEFAULT_FORM_VALUE),
};

export interface StorageBoxFormFeatureState extends FormGroupState<StorageboxFormValue> {
  boxId?: string;
}

export const reducer = createReducer(
  initialState,
  onNgrxForms(),
  on(AddStorageBox, (state) => {
    state = updateGroup(state, { name: setValue('') });
    return state;
  })
);
```

2. Update the form with `new SetValueAction(...)`. 
3. The `boxId` property in `StorageBoxFormFeatureState` will disappear. 

[Sand Box Link](https://codesandbox.io/s/ngrx-forms-issue-template-forked-zj0b2?file=/src/app/form.reducer.ts)

**Expected behavior**
In the above case, i would have expected `boxId` to remain rather than disappear from the state. 

**Library version**:
  "ngrx-forms": "^6.3.5"

**Comment by dzonatan** [comment]
This is intended behavior. Either use `userDefinedProperties` or nest the form state under its own property.

**Comment by AtozEvo** [comment]
Thats unfortunate. The 'persisting' behavior is seen in `@ngrx/entity` when extending a state with `EntityState` and updating the entities with the adapter, which is why i assumed that `ngrx-forms` would have behaved the same. Would there be any chance of this happening?

**Comment by MrWolfZ** [comment]
As @dzonatan wrote, this is indeed intentional behavior and this will not be changed. I recommend to place the form state in a separate field in the state:

```ts
export interface StorageBoxFormFeatureState {
  boxId?: string;
  formState: FormGroupState<StorageboxFormValue>;
}

export const reducer = createReducer(
  initialState,
  onNgrxForms(),
  on(AddStorageBox, (state) => {
    return { 
      ...state,
      formState: updateGroup(state.formState, { name: setValue('') }),
    };
  })
);
```
