### ISSUE TITLE
An array of FormGroupState?

### ISSUE THREAD

**Issue by philjones88** [MrWolfZ/ngrx-forms#26]
Let's say you want to build state like:

```
export interface MyForm {
   id: number;
   name: string;
}

export interface CustomState {
   foo: string;
   bar: string;
   myForm: FormGroupState<MyForm>;
}

export function reducer(state: CustomState[] = [], action: myActions.Actions): CustomState[] {
...
}
```

How would I go about applying `formGroupReducer` in this scenario where it's inside an array

**Comment by MrWolfZ** [comment]
If it is possible in your case to refactor the code to use a form array (i.e. `FormArrayState<MyForm>`) instead of an array of form groups you could use the `formArrayReducer`.

However, since you seem to need additional state per group there isn't really anything ngrx-forms can do to directly help you. In my own projects I handle these cases by having a separate reducer for a single item, and then having a utility method that maps the reducer over the array and tracks if any item changed, and if not return the original array. Not sure if that is the best way to do it, but it works for me so far. The whole thing looks roughly like this (once again untested so may contain bugs):

```typescript
function customStateReducer(state: CustomState, action: myActions.Actions) {
  // do the normal reduction with formGroupReducer etc.
  return state;
}

function createArrayReducer<T>(itemReducer: (item: T, action) => T) {
  return (state: T[], action: Action) => {
    let hasChanged = false;
    const newState = state.map(item => {
      const newItem = itemReducer(item, action);
      hasChanged = hasChanged || newItem !== item;
    });
    return hasChanged ? newState : state;
  };
}

function customStateArrayReducer(state: CustomState[], action: myActions.Actions) {
  return createArrayReducer(customStateReducer)(state, action);
}
```

**Comment by philjones88** [comment]
I'm going to remodel it to be all inside ngrx-forms and just accept `form.value.foo` bindings for the few properties that won't have direct controls.

I've got far but I'm struggling to find examples of `updateArray` with the equivilent of the`setValue` function to update 1 element of the array.

**Comment by MrWolfZ** [comment]
Indeed, that is a use case that I have not properly covered with the update functions. I'll put that on my TODO list (something like adding a filter function parameter to the updateArray function). For now you could use a helper function like this:

```typescript
function updateItemInFormArray<TValue>(
  state: FormArrayState<TValue>,
  index: number,
  updateFn: ProjectFn2<AbstractControlState<TValue>, FormArrayState<TValue>>,
) {
  return updateArray<TValue>(state, (control, array) => {
    if (control === array.controls[index]) {
      return updateFn(control, array);
    }

    return control;
  });
}
```

**Comment by philjones88** [comment]
Cool. Thanks for you help.

I figured out from the docs and source code updating a single item in `FormArrayState` isn't fully there and started using `addArrayControl` and `removeArrayControl` plus a less clean version of that example code you provided.

**Comment by philjones88** [comment]
The problem I'm hitting with your approach is setting none primative types, i.e. if you try to use `setValue` with an object you end up getting:

```
Error: Form control states only support undefined, null, string, number, and boolean values; got {"id":2,"name":"Foo" ....
```

and I can't get the right combination of parameters with `updateGroup` etc

**Comment by MrWolfZ** [comment]
`setValue` should work fine with groups. However, you need to ensure that it really is a group state. The error message you see indicates that you are trying to set an object value to a form control, which may happen e.g. if you initialize the groups with `null` as a value, which is then mapped to a control instead of a group.

**Comment by icepeng** [comment]
How about FormArray of FormGroup?

ex)
```
export const initialState: State = createFormGroupState<MyForm>(
  FORM_ID,
  {
    description: '',
    splits: [
      {
        name: '',
        salesTaxes: [],
      },
    ],
  },
);

const validationFormGroupReducer = createFormGroupReducerWithUpdate<
  MyForm
>({
  description: validate(required),
  splits: updateArray((control, array) => {
    return updateGroup({}); // ???
  }),
});
```

Is it possible to validate with `createFormGroupReducerWithUpdate`?

**Comment by icepeng** [comment]
```
export interface Split {
  name: string;
  tags: string[];
}
const validationFormGroupReducer = createFormGroupReducerWithUpdate<
  MyForm
>({
  description: validate(required),
  splits: updateArray(control => {
    return updateGroup<Split>({
      name: validate(required),
    })(control);
  }),
});
```

It seems working, might help @philjones88

**Comment by MrWolfZ** [comment]
@icepeng you can even get rid of some boilerplate since `updateGroup` returns a function matching what is expected in updateArray (YMMV regarding readability though):

```typescript
export interface Split {
  name: string;
  tags: string[];
}
const validationFormGroupReducer = createFormGroupReducerWithUpdate<MyForm>({
  description: validate(required),
  splits: updateArray(updateGroup<Split>({
      name: validate(required),
  })),
});
```

**Comment by icepeng** [comment]
@MrWolfZ I tried that first but get some errors. Will try again and update result

**Comment by MrWolfZ** [comment]
@icepeng I just checked and I am indeed missing a case in the typing of `updateArray` that makes the above example not compile. I'll fix it with the next version.

**Comment by MrWolfZ** [comment]
Closed due to inactivity. If you encounter any more problems feel free to open a new issue.

**Comment by vladimirdrayling** [comment]
Given the following structure:
```ts
interface Permissions {
  id: string;
  name: string;
  value: boolean;
}

interface Form {
  firstName: string;
  permissions: Permission[];
}
```

How can I check if at least one permission (checkbox) was selected?

### What I've tried

```ts
const validateForm = updateGroup<Form>('form', {
  firstName: validate(required),
  permissions: state => {
    if (state.isDirty && !state.value.some(permission => permission.value)) {
      setErrors(state, { missingPermission: true });
    }

    return state;
  },
});
```

I need to update the `Form['permissions']` based on checked checkboxes. The form is valid if at least one checkbox is checked.

Thanks for the help in advance!

**Comment by MrWolfZ** [comment]
@vladimirdrayling You're code is basically correct, it's just missing one tiny thing. You need to `return` the result of `setErrors`.
