### ISSUE TITLE
Angular Ivy Distribution

### ISSUE THREAD

**Issue by chuma2150** [MrWolfZ/ngrx-forms#260]
When installing packages with latest angular v13, a warning is popping up:
Processing legacy "View Engine" libraries:
- ngrx-forms [es2015/esm2015] (https://github.com/MrWolfZ/ngrx-forms.git)
Encourage the library authors to publish an Ivy distribution.

Thea reason for this is:
https://blog.angular.io/angular-v13-is-now-available-cce66f7bc296
Refer to point "State of View Engine"

**Comment by MrWolfZ** [comment]
I just released version [7.0.0](https://github.com/MrWolfZ/ngrx-forms/releases/tag/v7.0.0) which is published as an Ivy distribution.
