### ISSUE TITLE
Is this library still being maintained?

### ISSUE THREAD

**Issue by Thuurvdv** [MrWolfZ/ngrx-forms#261]
Last update has been 8 months ago.

**Comment by AtozEvo** [comment]
From my knowledge its still generally being maintained, but not as active. To be fair, there isn't much major issues and everything is still working.

**Comment by MrWolfZ** [comment]
The answer is "kinda". I am unfortunately not working actively in the Angular ecosystem anymore, so it is difficult to stay up to date with the latest changes and I'm honestly not super motivated to work on this library right now. That said, the library is specifically designed to have as little dependencies on Angular and ngrx as possible and provide maximum compatibility. And while there are some gaps (e.g. not using action creators for ngrx-forms actions), the library continues to work. I am of course always open to contributions that make the library more idiomatic for the latest ecosystem changes.
