### ISSUE TITLE
radio buttons don't mark as touched

### ISSUE THREAD

**Issue by philjones88** [MrWolfZ/ngrx-forms#28]
Given:

```
<div class="form-group">
    <label class="col-xs-3 control-label">Change state</label>
    <div class="col-xs-5">
        <div class="radio">
        <label>
            <input type="radio" name="stateRadios" value="online" [ngrxFormControlState]="(template$ | async)?.controls?.newTemplateState">
            Online
        </label>
        </div>
        <div class="radio">
        <label>
            <input type="radio" noBootstrap name="stateRadios" value="offline" [ngrxFormControlState]="(template$ | async)?.controls?.newTemplateState">
            Offline
        </label>
        </div>
    </div>
</div>
```

It issues a `SET_VALUE` and `MARK_AS_DIRTY` action but not a `MARK_AS_TOUCHED` action and I disable my button based on the form being touched.

If I focus another form element I then get a `MARK_AS_TOUCHED` action that enables my save button

**Comment by MrWolfZ** [comment]
That's how `MARK_AS_TOUCHED` is supposed to work. It is triggered once the form element loses focus. When you select a radio option it becomes focused and you have to click anywhere outside of the radio options for it to become blurred, which then marks it as touched.

As an alternative you could simply check `isDirty` or some combination of `isDirty` and `isTouched` depending on the form control.

**Comment by philjones88** [comment]
Thanks, changed to dirty as had feedback clicking away from controls to get the save button to enable was frustrating.
