### ISSUE TITLE
Is working on angular 14?

### ISSUE THREAD

**Issue by DavidCMeier** [MrWolfZ/ngrx-forms#281]
Hi! Someone test the library on Angular 14? i Asked because in Angular 14 the Reactive forms has change and now have types... and i don't know if maybe we have a problem if we updated our apps.

**Comment by mminor-dev** [comment]
I can't think of a a reason _why it would_.  ngrx-forms doesn't directly use ReactiveForms that I'm aware of.  ngrx-forms has had typing long before angular has gotten around to it. 

I created a simple stackblitz with all latest angular dependencies and things seemed to be working fine.

**Comment by MrWolfZ** [comment]
Indeed, the library works just fine on Angular 14.
