### ISSUE TITLE
How to implement nested form groups more than 2 levels deep

### ISSUE THREAD

**Issue by egonzal93** [MrWolfZ/ngrx-forms#29]
Hi,

I was using the dynamic forms reducer example, On my project I need 3 levels deep to add and remove items on my form. Are there any examples you can provide?

In the code, entityLocations should be a member of requestEntities. How do assign new EntityLocation to a specific RequestEntity?

RequestEntities['7df2d750-31c6-4314-860d-c07fe9a34c7c'].EntityLocations['6ddcb217-446b-4acb-b6a5-c92bde1b3282']: {
                    "Country": {
                        "PrimaryKey": "", 
                        "BusinessEntityNK": ""
                    }, 
                    "State": {
                        "PrimaryKey": "", 
                        "BusinessEntityNK": ""
                    }, 
                    "City": "Test CITY", 
                    "IsCrossBorder": false, 
                    "CreatedByUser": "", 
                    "UpdatedByUser": ""
                }

I also attached a sample of my reducer code.

[service-request.reducer.txt](https://github.com/MrWolfZ/ngrx-forms/files/1610166/service-request.reducer.txt)

![2018-01-07_15-07-09](https://user-images.githubusercontent.com/8977995/34653618-8bcd33fc-f3bc-11e7-8f21-c6e4534ba740.png)

**Comment by MrWolfZ** [comment]
You do an `updateGroup` for the correct entity based on the entity's ID (which I assume is included in the action). The whole thing would look like this:

```typescript
case CreateEntityLocationAction.TYPE:
  return updateGroup<ServiceRequestFormVM>({
    RequestEntities: updateGroup<{ [id: string]: EntityVM }>({
      [a.entityId]: updateGroup<EntityVM>({
        EntityLocations: locations => {
          const newValue = { ...locations.value, [a.locationId]: INITIAL_SERVICE_REQUEST_LOCATION_FORM_STATE };
          const newGroup = setValue(newValue, cast(locations));

          return newGroup;
        },
      }),
    }),
  })(s);
```

PS: I noticed you have a lot of constants for the initial form values. However, you call the form states, which is not really the case, i.e. I recommend renaming your constants from e.g. `INITIAL_SERVICE_REQUEST_LOCATION_FORM_STATE` to `INITIAL_SERVICE_REQUEST_LOCATION_FORM_VALUE`.

**Comment by egonzal93** [comment]
Thanks ill look into it

**Comment by MrWolfZ** [comment]
@egonzal93 anything else I can help with or can I close this issue?

**Comment by MrWolfZ** [comment]
Closed due to inactivity. Should you encounter more issues, feel free to open a new issue.
