### ISSUE TITLE
New Angular Version 15 with breaking changes on Material to mat-list-options

### ISSUE THREAD

**Issue by travishamera-hka** [MrWolfZ/ngrx-forms#301]
**Describe the bug**
I'm working through updates for Angular 15 including the breaking changes made for Angular Material and it's impacts, including my use of ngrx-forms.  I'm using your standard directive on mat-list-options to fix the ondestroy issue (MatListOptionFixDirective).  In the new update they have removed "selectionList" from matListOption which of course breaks the directive and brings down apps using ngrx-forms.  I haven't had the time to look into this further yet so posting this to see if anyone else gets to it first.

[Directive in github](https://github.com/MrWolfZ/ngrx-forms/blob/master/example-app/src/app/material/mat-list-option-fix.ts) 

**Library version**:
7.0.0  (looks to exist in 8.0.0 too)

**Comment by MrWolfZ** [comment]
Looking at the code, it seems there was simply a rename of the field from `selectionList` to `_selectionList`. Therefore maybe all it takes to fix the workaround directive is to change it as follows:

```ts
  constructor(@Host() private matDirective: MatListOption) { }

  ngOnDestroy() {
    // MatListOption does not have the properties below as public, so we
    // simply cast it to any and assume these properties exist
    const directive = this.matDirective as any;

    // for @angular/material <= 14
    if (directive.selectionList) {
      directive.selectionList = { _reportValueChange: () => void 0 } as any;
    }

    // for @angular/material >= 15
    if (directive._selectionList) {
      directive._selectionList = { _reportValueChange: () => void 0 } as any;
    }
  }
```

But the refactoring in material seems to have been quite big, so there could be other changes that cause an incompatibility.

**Comment by travishamera-hka** [comment]
Thanks for the quick update.  I'll go with this and then keep an eye out for more issue.  They really did change quite a lot!  Broke quite a few of my uses of material components and the css is change everywhere!

**Comment by travishamera-hka** [comment]
Confirming that MrWolfZ response is working for me.
