### ISSUE TITLE
Enable/Disable nested array properties

### ISSUE THREAD

**Issue by littleraeofsun** [MrWolfZ/ngrx-forms#312]
I have a form state structure that involves an array of objects where some properties on each object need to be enabled/disabled based on another property. I have examples of updating dynamic arrays and examples of enabling/disabling entities within the state, but I can't quite bridge the gap from disabling my individual controls and getting those updated controls back into my state.

Forgive me if there is an easy example of this somewhere, but I've pored through the docs and issues trying to find a means of accomplishing this to no avail :(

Here is a rough example of my situation:
```typescript
interface AddressState {
  type: string;
  street: string;
  poBox: string;
  note: string;
}

interface FormState {
  name: string;
  age: number;
  addresses: AddressState[];
}

interface FeatureState {
  recordId: number;
  recordStatus: string;
  form: FormGroupState<FormState>;
}

interface RootState {
  feature1: any;
  feature2: any;
  formFeature: FeatureState;
}
```

```typescript
// in the reducer for the formFeature: FeatureState
on(handleAddressTypeChange, (state, action) => {

  // fetch the address indicated by the action index
  var address = {...state.form.value.addresses[action.index]};

  // only Mailing addresses can have a POBox
  if (action.addressType !== CustomHandlingAddressTypes.MAILING) {
    address.poBox = '';
    // TODO: disable poBox for this address
  }
  // only Other addresses can have a note
  if (action.addressType !== CustomHandlingAddressTypes.OTHER) {
    address.note = '';
    // TODO: disable note for this address
  }
  
  // update the form state with the new address
  var curArray = state.form.controls.addresses.value;
  var newArray = [...curArray.slice(0, action.index), address, ...curArray.slice(action.index+ 1)];
  var newForm = updateGroup(state.form, { addresses: setValue(newArray) });
  return { ...state, form: newForm };
})
```

I followed the example provided [here in issue 157](https://github.com/MrWolfZ/ngrx-forms/issues/157) to handle clearing out the values of by Dynamic Array object, and I realize that I can use the `enable()` and `disable()` methods you provide on the `poBox` and `note` controls of a given `FormGroupState<AddressState>` object, but I don't know how to graft that child group back into the array or my overall state.

Any direction would be appreciated!

**Comment by littleraeofsun** [comment]
So after a bit more work with the ngrx-forms library, I managed to scrape together a solution using an Effect to emit DisableAction and EnableAction as necessary. Here's a rough translation of my implementation based on the example I provided above:

```typescript
  addressTypeChanged$ = createEffect(() => this.actions$.pipe(
    ofType(SetValueAction.TYPE),
    filter((action: SetValueAction<number>) => action.controlId.indexOf('type') > 0), // my "type" property on my address model is actually "addressTypeCodeId" which better distinguishes the actions that I want; I imagine "type" would be too generic to use by itself here
    withLatestFrom(this.store),
    map(([action, state]) => {
      // setup results action set
      const resultingActions: (DisableAction | EnableAction | SetValueAction<string>)[] = [];

      // harvest index from control id
      const index = action.controlId.match(/\d+/g)?.map(Number)[0];

      if (index !== undefined) {
        const addressControl = state.formFeature.form.controls.addresses.controls[index];

        // only Mailing type addresses can have a POBox
        if (action.value === CustomHandlingAddressTypes.MAILING) {
          resultingActions.push(new EnableAction(addressControl.controls.poBox.id));
        } else {
          resultingActions.push(new DisableAction(addressControl.controls.poBox.id));
          resultingActions.push(new SetValueAction(addressControl.controls.poBox.id, ''));
        }

        // only Other type addresses can have a Note
        if (action.value === CustomHandlingAddressTypes.OTHER) {
          resultingActions.push(new EnableAction(addressControl.controls.note.id));
        } else {
          resultingActions.push(new DisableAction(addressControl.controls.note.id));
          resultingActions.push(new SetValueAction(addressControl.controls.note.id, ''));
        }
      }

      return resultingActions;
    }),
    mergeAll()
  ));
```

This appears to be doing exactly what I want (though I did have to setup an additional action for when a new Address is added to disable the poBox and note properties by default).

**Comment by MrWolfZ** [comment]
Hi there. Effects should almost never be necessary in order to update the state. The core idea of **ngrx-forms** is to model your form dependencies as declaratively as possible, while sometimes using escape hatches where imperative logic is required (as is the case here when you want to have a relationship between sibling properties).

In your case, you can create a form update function that enables or disables (and clears) the other controls depending on the address type like this:

```ts
// first, create an update function that acts on a single address group
const updateAddress = updateGroup<AddressState>({
  // use the long-hand form of an update function that allows accessing sibling properties
  poBox: (c, parent) => {
    // here you can access the address type through the parent state value
    if (parent.value.type == CustomHandlingAddressTypes.MAILING) {
      return enable(c);
    } else {
      return disable(setValue(c, ''));
    }
  },
  note: (c, parent) => {
    if (parent.value.type == CustomHandlingAddressTypes.OTHER) {
      return enable(c);
    } else {
      return disable(setValue(c, ''));
    }
  },
});

// then, execute an update on the whole form which updates every address control in the array; any address that
// hasn't changed will stay as is, while the single address whose type has changed will be updated
updateGroup(state.form, { addresses: updateArray(updateAddress) });
```

There is documentation about this [here](https://ngrx-forms.readthedocs.io/en/master/user-guide/updating-the-state/#updating-groups), but it is admittedly difficult to find.

**Comment by littleraeofsun** [comment]
It turns out in this event I actually had to pull data from a different part of the state in order to determine whether to enable or disable (an independently loaded set of options arrays), so this approach did wind up having to be an effect.

However, I was able to incorporate this enable/disable dependency chaining into a different validator setup (which I wrap into my reducer with `wrapReducerWithFormStateUpdate`), and for the most part it is working very nicely:

```typescript
// interfaces.ts
interface Alias {
  firstName: string;
  middleName: string;
  lastName: string;
  isNickname: boolean;
}

// reducers.ts
import { updateGroup, validate, disable, enable, setValue } from 'ngrx-forms';
import { required } from 'ngrx-forms/validation';

const aliasValidation = updateGroup<Alias>({
  firstName: validate(required),
  middleName: (control, parent) => {
    if (parent.value.isNickname) {
      return disable(setValue(control, ''));
    }
    else {
      return enable(control);
    }
  },
  lastName: (control, parent) => {
    if (parent.value.isNickname) {
      return disable(setValue(control, ''));
    }
    else {
      return enable(control);
    }
  }
});
```

My current issue that I would like the `lastName` property to be required when it is enabled, but not when it is disabled. I followed the example you have in the [Declarative vs Imperative Updates](https://ngrx-forms.readthedocs.io/en/master/user-guide/updating-the-state/#declarative-vs-imperative-updates) section that shows combining the enable/disable with a validate, but when I use the syntax:

```typescript
  lastName: (control, parent) => {
    control = (parent.value.isNickname) ? disable(setValue(control, '')) : enable(control);
    return validate(required)(control);
  }
```
I receive a rather nasty error message on the entire `updateGroup` regarding type mismatches. What am I doing wrong?

> No overload matches this call.
  Overload 1 of 4, '(updateFn: StateUpdateFns<Alias>, ...updateFnsArr: StateUpdateFns<Alias>[]): (state: FormGroupState<...>) => FormGroupState<...>', gave the following error.
    Type '(control: FormControlState<string>, parent: FormGroupState<Alias>) => FormControlState<string> | FormGroupState<...>' is not assignable to type 'ProjectFn2<FormControlState<string>, FormGroupState<Alias>>'.
      Type 'FormControlState<string> | FormGroupState<Boxed<string>>' is not assignable to type 'FormControlState<string>'.
        Type 'FormGroupState<Boxed<string>>' is missing the following properties from type 'FormControlState<string>': isFocused, isUnfocused
  Overload 2 of 4, '(updateFnsArr: StateUpdateFns<Alias>[]): (state: FormGroupState<Alias>) => FormGroupState<...>', gave the following error.
    Argument of type '{ firstName: (state: AbstractControlState<string>) => FormControlState<string>; middleName: (control: FormControlState<string>, parent: FormGroupState<...>) => FormControlState<...>; lastName: (control: FormControlState<...>, parent: FormGroupState<...>) => FormControlState<...> | FormGroupState<...>;' is not assignable to parameter of type 'StateUpdateFns<Alias>[]'.
      Object literal may only specify known properties, and 'firstName' does not exist in type 'StateUpdateFns<Alias>[]'.ts(2769)
interfaces.ts(75, 3): The expected type comes from property 'lastName' which is declared here on type 'StateUpdateFns<Alias>'
