### ISSUE TITLE
Nested form: 'The control state must not be undefined!'

### ISSUE THREAD

**Issue by blissi** [MrWolfZ/ngrx-forms#35]
Hallo,
I've got a nested form that is several levels deep:

```
export const initialShippingEditorFormState = createFormGroupState<ShippingEditorForm>(SHIPPING_EDITOR_FORM_ID, {
	ups: {
		extraServices: {
			...
		}...
	},
	...
});
```

I have a root Angular component that's bound to the root form state. Each nested form state has an own component that's also bound. In the root component the binding looks like this:
```
<form [ngrxFormState]="formState$ | async">
     ....
     <ups-overview [formState]="(formState$ | async).controls.ups"></ups-overview>
     ...
```

The binding in ups-overview looks like this:
```
<ups-extra-services [formState]="formState.controls.extraServices"></ups-overview>
```

Please note that formState$ in the root is an _Observable<FormGroupState<T>>_ and in the child components it's just an _@Input() FormGroupState<T>_. Now when I run the application I get the error 'The control state must not be undefined!' within ngrx-forms code for the ups-extra-services component.

I debugged it by setting a breakpoint at the location where the exception is thrown and within the setter of the formState-input-property:
ngrx-form is called first, before the data binding took place.

Do you have any suggestion how I could fix this problem?

**Comment by MrWolfZ** [comment]
Why are you using the async pipe in ups-extra-services if the input is not an observable? What happens if you remove the pipe?

**Comment by blissi** [comment]
Sorry may mistake...I didn't copy&paste my sources, but manually typed the HTML since I'm using Jade. In my code the binding looks as you suggested.

**Comment by MrWolfZ** [comment]
The setter for the form state is always called as part of the data binding process. Therefore, if it is undefined then there is either an error in the binding itself (e.g  accessing a non-existing control, having a typo etc.) or the form state really is undefined in the state.
Have you built your app with `ng build -prod` to have AoT verify your bindings? And could you post your component and reducer code?

**Comment by blissi** [comment]
Omg you're right...I had a typo in one of the bindings. Thanks for pushing me into the right direction!

**Comment by patricknazar** [comment]
FYI to anyone wondering - this same error can occur when you forget to put `.controls.` in `formState.controls.myControl`, I had `formState.myControl` and yeah just threw me off a bit.
