### ISSUE TITLE
Reducer action firing multiple times-please close, I resolved it. I have to add a sender on the payload and then filter the owner of the action

### ISSUE THREAD

**Issue by egonzal93** [MrWolfZ/ngrx-forms#36]
Hi,

I have an issue where my update action is firing unintentionally inside of the reducer:

Here is what my model looks like:

export interface EntityVM {
  EntityDescription: string;
  EntityLocations: { [ id: string]: EntityLocationVM };
}

export interface EntityLocationVM {
  _id: string;
  ParentEntity: string;
  City: string;
}

If I have this:

const data = {
  EntityDescription: 'test',
  EntityLocations: {
    ['100']: {
      _id: 1000,
      ParentEntity: '200',
      City: 'test100'
    },
    ['200']: {
      _id: 2000,
      ParentEntity: '200',
      City: 'test200'
    }
  }
};

If just trigger an update on _id = 2000 with City='test123', 2 reducer actions gets fired making the values change to both _id=1000 and _id=2000 City to 'test123', should only update the City on _id=2000 but instead it updated all the data because it fired 2 times, it should have only fired the reducer action only once. 

 case UpdateCityAction.TYPE:

      return updateGroup<EntityVM>({

        EntityLocations: updateGroup<{ [id: string]: EntityLocationVM }> ({

          [a.payload.id]: updateGroup<any>({

            City: city => {

              const newVal = setValue(a.payload.data, cast(city));

              return newVal;
            },
          }),
        }),
      })(s);

Is there a way around this issue?

Thanks

**Comment by MrWolfZ** [comment]
Can you elaborate which action fired twice? Your own one or an ngrx-forms one? What is the value of `a.payload.id` in your example? Also, could you please post the full form state at the point the issue happens? You can do this either by copy/pasting from redux dev tools (if you use that) or adding something like `{{ formState$ | async | json }}` to your HTML template (that's something I do fairly regularly myself for debugging).

From just looking at your data and code the ID of the entity location you need to update seems to be `200`, not `2000`. Is that a typo?

**Comment by egonzal93** [comment]
Hi,

So here is what its supposed to do:
1. You select a country, the states dropdown populates with states from that country.
2. Changing the country, changes ALL the state dropdown  EntityLocationVM's on the list.
3. So the action to change a state dropdown triggers an update on ALL EntityLocationVM on the list.
4. Initially, when I add a new EntityLocationVM each state dropdown has its own set of initial values.
5. On this example the UPDATE_STATE_BY_COUNTRY was triggered 3 times, even though I only changed the value on the 2nd items.
6. The values you see on each drop down is the unique ID of each EntityLocationVM 

**UNIQUE ID of each EntityLocationVM** 

![2018-01-16_10-01-22](https://user-images.githubusercontent.com/8977995/35187006-4d490a8c-fdeb-11e7-9c30-0710ad7a9688.png)

![2018-01-20_13-54-05](https://user-images.githubusercontent.com/8977995/35187011-54a6490c-fdeb-11e7-8ee0-f5a110ef6b0b.png)

![2018-01-20_13-54-05](https://user-images.githubusercontent.com/8977995/35187020-677fa42e-fdeb-11e7-8621-6743db28a8a4.png)

**SELECTED THE MIDDLE EntityLocationVM , it should only update single states dropdown** 

![2018-01-20_13-54-40](https://user-images.githubusercontent.com/8977995/35187014-59ab4326-fdeb-11e7-9b83-58b2e0a8df2c.png)

**3 actions fires from a single item change**

![2018-01-20_13-55-14](https://user-images.githubusercontent.com/8977995/35187017-5f9d2eac-fdeb-11e7-8021-ec515e3fca61.png)

**The debug console confirms it.**

![2018-01-20_14-05-27](https://user-images.githubusercontent.com/8977995/35187019-63d8c742-fdeb-11e7-96e2-2b5430e8552d.png)

**The side effects after that single change, all state dropdown are now identical**

![2018-01-20_14-11-42](https://user-images.githubusercontent.com/8977995/35187078-22dd0f7c-fdec-11e7-933b-ff952269dbb3.png)
![2018-01-20_14-11-54](https://user-images.githubusercontent.com/8977995/35187080-2ad675ce-fdec-11e7-8c6e-25385857be42.png)

**Comment by egonzal93** [comment]
These are how the component are created:

![2018-01-20_15-46-57](https://user-images.githubusercontent.com/8977995/35187865-6ecc8aa4-fdf9-11e7-85b2-4726777f2ca1.png)
![2018-01-20_15-47-27](https://user-images.githubusercontent.com/8977995/35187866-71079700-fdf9-11e7-8386-da42bf737720.png)
![2018-01-20_15-47-44](https://user-images.githubusercontent.com/8977995/35187868-72fe193a-fdf9-11e7-98e3-f4d6cae5633c.png)

**Once a a response from the API is received, the address reducers states list is passed to update the EntityLocationVM model state.**

![2018-01-20_15-52-55](https://user-images.githubusercontent.com/8977995/35187895-043c6762-fdfa-11e7-87e8-7dda5dee27b6.png)


**Once a country is selected, this function is triggered**

![2018-01-20_15-49-48](https://user-images.githubusercontent.com/8977995/35187877-9b607080-fdf9-11e7-9fc0-a1fd92df12e9.png)

**Comment by MrWolfZ** [comment]
Hmm, I don't really see how ngrx-forms could be responsible for the duplicate actions since it only knows (and triggers) its own actions.

Two things I noticed though:

1. You are using a `mat-select` without the `ngrxFormControlState` attribute. That means it is not using ngrx-forms at all for that select. Is this what you intended?
2. In the second to last screenshot you set up a subscription on the store but don't store the subscription anywhere. That implies you are never unsubscribing from this. Depending on how you set this up it might explain why you see duplicate actions being triggered since you potentially have multiple concurrent subscriptions on the `s.addressReducer.states`.

**Comment by egonzal93** [comment]
It looks like its the component issue. here is work around on the code logic:

**I only populate the state dropdown if the subscription was made by the component that dispatches it.**

![2018-01-21_21-11-24](https://user-images.githubusercontent.com/8977995/35202267-a9b0ca9e-feef-11e7-85fb-f66e858d7ccb.png)

**Once a country is selected an API call is made**

![2018-01-21_21-16-59](https://user-images.githubusercontent.com/8977995/35202388-7309d8ae-fef0-11e7-8bba-ff8a4deacbe5.png)

**The effects appends the sender object once the API call is finished.**

![2018-01-21_21-12-48](https://user-images.githubusercontent.com/8977995/35202318-e3b979e8-feef-11e7-82bc-723ad8867eb4.png)

The state reducer applies the new list:

![2018-01-21_21-15-07](https://user-images.githubusercontent.com/8977995/35202360-415aeac8-fef0-11e7-8c46-5d2bf7a0fd34.png)
