### ISSUE TITLE
Select element doesn't work properly with non-string values (a la ngValue)

### ISSUE THREAD

**Issue by nathanmarks** [MrWolfZ/ngrx-forms#4]
https://github.com/angular/angular/blob/32ff21c16bf1833d2da9f8e2ec8536f7a13f92de/packages/forms/src/directives/select_control_value_accessor.ts#L176

Because of the extended value accessor, `this._select` is null meaning that `ngValue` cannot be used.

Is there a way around this so we can use select elements with non string values?

**Comment by MrWolfZ** [comment]
Well, I could probably export the derived value accessor as a `SelectValueAccessor` which would allow `NgOption` to inject it. However, there's a general issue with using objects as form values. Currently, ngrx-forms is written in such a way that an object is always interpreted as a form group and only simple primitive values (booleans, strings, numbers) are allowed for form controls. That was a conscious design decision that allows making certain parts of the API much nicer. Changing this would mean reworking most of the core of ngrx-forms which I don't really want to do. I will still try to implement this fix, but it will lead to an exception at runtime if you try to set a complex object as the value of the form control. Therefore my suggestion for this would be to simply use some identifier for the object as the control value and then access the object by ID later in your code. If your object does not have an ID by itself you should be able to use the index inside the array as the value.

**Comment by MrWolfZ** [comment]
I added support for `ngValue` in version 1.0.2 which I just released.
