### ISSUE TITLE
Dynamic Array of Objects 

### ISSUE THREAD

**Issue by Kaffiend** [MrWolfZ/ngrx-forms#43]
I'm still wrapping my head around everything here and i'm curious how one would implement a dynamic list of objects. 

```
interface Person {
surname: string;
givenName: string;
middleName: string;
}
```

![image](https://user-images.githubusercontent.com/7826229/35871019-2bb51156-0b31-11e8-8e81-c9267db8b53e.png)
i'd like to add a new entity each time the last one is filled in. I'm just not sure about the form implementation. As usual, i'm probably over-thinking this..

would i just use a normal array and handle it in 3's with the reducer and such and parse out the values into the model structure?

**Comment by MrWolfZ** [comment]
Sure, you can simply use a form array, i.e. something like this:

```typescript
interface Person {
  surname: string;
  givenName: string;
  middleName: string;
}

const initialPersonFormValue: Person = {
  surname: '',
  givenName: '',
  middleName: '',
};

const initialState: FormArrayState<Person> = createFormArrayState<Person>('form ID', [
  initialPersonFormValue,
  initialPersonFormValue,
]);

// and then just access the form state's value like this
const persons: Person[] = initialState.value;

// you can add new person forms like this:
const newState = addArrayControl(initialPersonFormValue, initialState);

// or dispatch an action somewhere in a component
actionSubject.next(new AddArrayControlAction(arrayFormState.id, initialPersonFormValue));
```

In your template simply iterate over the form controls:

```html
<form [ngrxFormState]="arrayFormState">
  <div *ngFor="let personGroup of arrayFormState.controls">
    <input [ngrxFormControlState]="personGroup.controls.surname" >
    <input [ngrxFormControlState]="personGroup.controls.givenName" >
    <input [ngrxFormControlState]="personGroup.controls.middleName" >
  </div>
</form>
```

**Comment by Kaffiend** [comment]
yes indeed, i was in fact waay over-thinking it. Thank you, that makes sense now

**Comment by MrWolfZ** [comment]
Closing this. If you have any other questions feel free to open another issue.
