### ISSUE TITLE
Ngrx-forms and Angular Material

### ISSUE THREAD

**Issue by jacqui932** [MrWolfZ/ngrx-forms#51]
Hi,

Thanks for the help you gave me earlier - much appreciated.  I have a new problem now:

I am trying to change my entry form to use angular material.  I have the following:
```
<mat-form-field>
  <input matInput placeholder="Name"
    [ngrxFormControlState]="entryForm.controls.name" required/>
  <mat-error *ngIf="!entryForm.controls.name.isValid && entryForm.controls.name.isTouched">
    You must enter a name.
  </mat-error>
</mat-form-field>
```

but the error message is not being displayed even though I can see in devtools that 'isValid' is false and 'isTouched' is true.

Is there something I need to do to get this to work properly?

**Comment by MrWolfZ** [comment]
I believe [this issue](https://github.com/MrWolfZ/ngrx-forms/issues/50) will answer your question :)

**Comment by jacqui932** [comment]
Brilliant - thank you (again) :-)
