### ISSUE TITLE
Control Value Accessor

### ISSUE THREAD

**Issue by ghtjiann4321** [MrWolfZ/ngrx-forms#52]
Good Day,

I'm a little confused with the control value accessor to be used. I am trying to create a custom form control but sadly it isn't working. I also tried using the form view adapter in the documentation. It logs the writeValue() method but when I am triggering the propagateChange(newValue) function it's not updating the state. 

`
clearSelection() {
    const selected = _.cloneDeep(this.selected)
    this.selected = []
    // this.selectDeselect.emit(this.selected)
    this.propagateChange(this.selected)
  }

  writeValue(value: any) {
    if (value !== undefined) {
      this.selected = value
    }
  }

  propagateChange = (value: any) => {}
  registerOnChange(fn: (value: any) => void): void {
    this.propagateChange = fn
  }

  registerOnTouched(fn: () => void) {}
`
My custom component

`
<comp [ngrxFormControlState]="(myFormState$ | async).controls.group"></comp>
`

Thanks!

**Comment by MrWolfZ** [comment]
The only thing I notice from your code is that you are trying to set an array as the value. That is not supported for form controls, except if you are using a value converter. Is your control similar to a multiple select? If so have a look at the value converter example in the example app to see how to use it.

Alternatively you could also simply debug into the `propagateChange` call to see what is happening.

**Comment by MrWolfZ** [comment]
Could you solve your issue by now?

**Comment by MrWolfZ** [comment]
Closed due to inactivity. If you still encounter issues feel free to post here again and I'll reopen the issue.
