### ISSUE TITLE
Question: how to handle api submission errors?

### ISSUE THREAD

**Issue by Drammy** [MrWolfZ/ngrx-forms#53]
I'm using ngrx-forms (great code btw!) and have a situation where administrators can sign up new users in a user creation form.

The thing is, if they submit a username that already exists our API returns an exception.

I'm handling the exception with ngrx effects and displaying a snackbar (angular app) but the exception seems to leave my form.value in an inconsistent state.

Should ngrx handle this scenario out of the box?

**Comment by Drammy** [comment]
I've fixed a problem that was causing the state inconsistencies so I can now see the form state..

I can now see the form is an 'isSubmitted: true' state.

I've added called 'MarkAsUnsubmitted' on my failure effect and it now returns to the expected, 
non submitted state.

Is this how you would achieve the same thing?

**Comment by MrWolfZ** [comment]
Sorry for the late response. The way I handle API errors is exactly as you describe. I handle the error response by using something like `.catch(response => new HandleApiErrorAction(response));`. In addition, if you need to mark the form state as unsubmitted (I guess you need this to reset the error display or something similar?) you simply dispatch a `MarkAsUnsubmittedAction`.

**Comment by Drammy** [comment]
That's great, thanks for confirming!

**Comment by warren32** [comment]
Is the only way to respond to an API error to dispatch an action and for example, display a snack bar?  The API I'm working with returns specific errors for each FormControl. Something like:
```
{
     email: 'Invalid email address'
}
```
I can see it's possible to update the errors at the control level via `const updatedControl = setErrors({ missing: true })(control);` and I also see that's its possible to update the form group via `const updatedGroup = setErrors({ innerMissing: true })(group);`  Would it be possible to attach the new `updatedControl` to the `updatedGroup` so that it will update both the control and the group?

**Comment by MrWolfZ** [comment]
@warren32 How you handle your API errors completely depends on what you need to do with the returned error. As you say, you can either just dispatch a `SetErrorsAction` for the control ID or you can dispatch your own custom action and then inside the reducer use `setErrors` (see below for how to update the nested control). With the action the only thing that happens is that the errors and validity of the form state are updated. With a custom action you can run additional logic if that is required. From your example response I would go for the action.

To update the nested control just use this code:

```typescript
const updatedFormState = updateGroup(formState, {
  innerControl: setErrors({ missing: true }),
});
```

This way the control inside the group is updated with the errors and the group's validity and errors are also updated.

**Comment by warren32** [comment]
Thank you for your reply.  I ended up realizing that `updateGroup` is the correct method to use here.

```
// update the submitted state of the form as suggested by @Drammy 
const unsubmittedViaAction = formStateReducer(formState, new MarkAsUnsubmittedAction(formState.id)); 

// update the FormControlState.
const finalState = updateGroup<LoginForm>(currentState, {
                email: (e: FormControlState<string>) => {
                    return setErrors({
                          server: action.payload.error
                    })(e);
                }
            });
```
After reading the documentation I see that `updateGroup` will recompute the FormGroupState after updating the FormControlState which is the desired effect here.
