### ISSUE TITLE
Howto - validation of dependent state fields without group

### ISSUE THREAD

**Issue by stgrosshh** [MrWolfZ/ngrx-forms#55]
May be I'm not clever enough, but how can one do validation of dependent fields in state without
a group?
The examples are handling groups only (like the nested stuff from user guide or password stuff from the example app).

I do not want to nest the fields and introduce a over-engineered handling on backend side.
Use case is that two fields in the state have to have different values.

**Comment by stgrosshh** [comment]
Sure. For example:
export interface Signatures {
  signee1:string
  signee2:string
}

Signee1 must not be the same value as Signee2 besides being required fields.

**Comment by MrWolfZ** [comment]
Well, that is a group. Any object form value will be a form group. Therefore you can use the same tools that are demonstrated in the password example. Below is the full code for your concrete case:

```typescript
export interface Signatures {
  signee1: string;
  signee2: string;
}

const formState = createFormGroupState<Signatures>('SIGNATURES_FORM_STATE', {
  signee1: '',
  signee2: '',
});

// this should really by a pre-defined validation
// function from ngrx-forms; I've added it to my
// TODO list for the next release
export function notEqualTo<T>(comparand: T) {
  return (value: T): ValidationErrors => {
    if (value !== comparand) {
      return {};
    }

    return {
      notEqualTo: {
        value,
      },
    };
  };
}

const formStateReducer = createFormGroupReducerWithUpdate<Signatures>({
  signee1: validate<string>(required),
  signee2: (signee2, signatures) =>
    validate([
      required,
      notEqualTo(signatures.value.signee1),
    ], signee2),
});

// or as a simple form state update
const validateFormState = updateGroup<Signatures>({
  signee1: validate<string>(required),
  signee2: (signee2, signatures) =>
    validate([
      required,
      notEqualTo(signatures.value.signee1),
    ], signee2),
});

const validatedFormState = validateFormState(formState);
```

**Comment by stgrosshh** [comment]
Ah I see, thanks. 
Will try that.

**Comment by MrWolfZ** [comment]
Closed due to inactivity. If you have any more questions feel free to open another issue.
