### ISSUE TITLE
Example app tests

### ISSUE THREAD

**Issue by bufke** [MrWolfZ/ngrx-forms#58]
I noticed the example app component tests do not pass. What do you think of adding tests that show off how one would want to make tests when using this? I started [some](https://gitlab.com/passit/passit-frontend/blob/67558f5f8330c89c9a3d7b2bf9d1c52a86e4ea4d/src/app/account/login/login.component.spec.ts) for my project. It's always tricky for me to think what the right way to test is. Initial thoughts:

- I needed to add an empty state `StoreModule.forRoot({})` to make the test run without DI errors
- I set the form group like this `component.form = updateFormGroup(initialState.form);`
- I test the component by setting up some validation issues in the FormGroupState and checking how the component renders

**Comment by MrWolfZ** [comment]
I have just released version [3.0.0](https://github.com/MrWolfZ/ngrx-forms/releases/tag/v3.0.0) which contains some example tests in the example app (although I will add some more in future).

**Comment by marcelnem** [comment]
I found some tests for reducers, any example of how we could test a component that contains ngrx-form?

**Comment by MrWolfZ** [comment]
@marcelnem Not in the example app, but there are some component tests in the library itself. Have a look [here](https://github.com/MrWolfZ/ngrx-forms/blob/master/src/control/e2e.spec/select.spec.ts) for example. It all depends on what you want to test though. If you wanted to test that all the correct controls are passed in the bindings you could create a mock form state and set a specific value for each property, and then verify the `value` attribute of the `input`s matches.
