### ISSUE TITLE
It does not work with @angular/material 5.2.4 for showing mat-error on input error

### ISSUE THREAD

**Issue by xiongemi** [MrWolfZ/ngrx-forms#61]
It does not work with @angular/material 5.2.4 input and error.
For angular material, when the input has errors, it should mat-error if you put the input and mat-error under mat-form-field. However, since material expects a control under mat-form-field, it does not show the mat-error.

```js
<mat-form-field class="w-100" *ngIf="(formState$ | async)?.controls?.email as email" #formField>
    <input
      name="email"
      type="email"
      matInput
      placeholder="Email"
      [ngrxFormControlState]="email"
      required>
    <mat-error>
      Please enter a valid email address
    </mat-error>
  </mat-form-field>
```

Is there any way to hack around using this library?

**Comment by MrWolfZ** [comment]
Sadly material only properly integrates with `@angular/forms` for the error handling. You need to build your own custom error state matcher. Have a look at [this issue](https://github.com/MrWolfZ/ngrx-forms/issues/50) for the description of what to do.

I'll make sure to add an entry to the upcoming FAQ about this and I'll also mention it in the HTML and description of the material example in the example application.
