### ISSUE TITLE
Material Selects - Error: No valid view adapter!

### ISSUE THREAD

**Issue by NF997** [MrWolfZ/ngrx-forms#62]
Hello again,

in fact, I've yet another question:
My inputs and my checkboxes work perfectly fine with Angular Material, but unfortunately, there is a problem with my selects.
When I try to display a selct exactly the way you did it in the example app:

``` html
 <div>
    <mat-form-field>
      <mat-select placeholder="Favorite Color"
                  [ngrxFormControlState]="question">
        <mat-option value=""></mat-option>
        <mat-option value="ff0000">Red</mat-option>
        <mat-option value="00ff00">Green</mat-option>
        <mat-option value="0000ff">Blue</mat-option>
      </mat-select>
    </mat-form-field>
 </div>
```

I get the follwoing error in the console: 

``` red
QuestionDropdownComponent.html:27 ERROR Error: No valid view adapter!
    at selectViewAdapter (forms.es5.js:3404)
    at new NgrxFormControlDirective (forms.es5.js:3451)
    at createClass (core.js:12432)
    at createDirectiveInstance (core.js:12267)
    at createViewNodes (core.js:13725)
    at callViewAction (core.js:14159)
    at execComponentViewsAction (core.js:14068)
    at createViewNodes (core.js:13753)
    at createRootView (core.js:13614)
    at callWithDebugContext (core.js:15039)
```

The issue is definitely related to Angular Material since everything works just fine with the "native" select.
Do you have any ideas why I'm facing this problem?
I'm using Angular Material 5.2.5, but even with older versions the error doesn't disappear.

Thanks in advance!

**Comment by NF997** [comment]
Works perfectly - thanks a lot!

**Comment by fxck** [comment]
@MrWolfZ can you link me to the issue they refused to do the change?

**Comment by fxck** [comment]
I'm trying to use `mat-select-trigger` but for whatever reason it doesn't register the initial value and shows up only after I select different value. I wonder if it has anything to do with those adapter fixes..

**Comment by fxck** [comment]
Hm nope, it has nothing to do with mat-select-trigger, it doesn't show the initial value at all.

**Comment by MrWolfZ** [comment]
@fxck [this](https://github.com/angular/material2/issues/6549) is the issue.

**Comment by Yohandah** [comment]
One easy solution is to use the native select
```
<h4>Basic native select</h4>
<mat-form-field appearance="fill">
  <mat-label>Cars</mat-label>
  <select matNativeControl required>
    <option value="volvo">Volvo</option>
    <option value="saab">Saab</option>
    <option value="mercedes">Mercedes</option>
    <option value="audi">Audi</option>
  </select>
</mat-form-field>
```
