### ISSUE TITLE
Reducer-Problem with array of FormGroupState

### ISSUE THREAD

**Issue by NF997** [MrWolfZ/ngrx-forms#66]
Since I need to store multiple (could be 1, could be 100) form states which get initiated dynamically (I don't know the configuration of them in advance), I tried to store them as an `Array<FormGroupState<QuotesFormValue>>`. 

When I now try to call formGroupReducer() - which I think I need to do to update my form state (e.g. on SET_VALUE) - on every FormGroupState of my array:
`const quotesForms = state.quotesForms.map(qF => formGroupReducer(qF, action));`
I face a problem: When I click in a input field and type a character, the store updates the value of the appropriate control and sets other values like isDirty etc. correctly. 
However, immediately after typing this character my input looses focus.

Here are my reducer and my component:

```
export interface QuotesFormValue {
  [controlId: string]: any;
}

export interface State {
  quotes: IQuote;
  quotesForms: Array<FormGroupState<QuotesFormValue>>;
}

const initialState: State = {
  quotes: null,
  quotesForms: []
};

export function reducer(state = initialState, action: quotesActions.Actions): State {

  const quotesForms = state.quotesForms.map(qF => formGroupReducer(qF, action));
  if (quotesForms !== state.quotesForms) {
    state = { ...state, quotesForms };
  }

  switch (action.type) {
  // ...
    default:
      return state;
  }
}
```

```
<div *ngIf='quotesFormStates$ | async as quotes; else statusMessageWithoutQuotes'>
        <div>
            <div *ngFor="let quoteOption of quotes;">
                <mat-card>
                    <form novalidate [ngrxFormState]="quoteOption">
                        <div *ngIf="quoteOption">
                            <ng-container *ngFor="let question of getKeys(quoteOption.controls)" question [question]="quoteOption.controls[question]"></ng-container>
                        </div>
                    </form>
                    <button mat-raised-button color="primary" (click)="recalculate(quoteOption.id)">
                        Recalculate
                    </button>
                </mat-card>
            </div>
        </div>
    </div>
```

I generate my controls dynamically, but the problem can't lie there since they work perfectly fine with other NGRX forms (where I do not store an array of FormGroupState).

Thanks in advance!

**Comment by MrWolfZ** [comment]
Use a trackBy on the *ngFor, that will solve the focus problem. You can track by the control ID. The reason is that the form state reference/identity changes after every update due to how ngrx works which forces angular to rerender the whole for loop. By using trackBy Angular will keep the same DOM nodes around.

PS: Instead of doing Array<FormGroupState> you could also just use single FormArrayState. The advantage is that the form array will track if any child group is invalid etc. If you don’t need this then just an array of groups is perfectly fine.

**Comment by NF997** [comment]
Works like a charm - thanks a lot for the quick answer!
