### ISSUE TITLE
Removing items from array with some items looses the isDirty flag when it's empty

### ISSUE THREAD

**Issue by lucax88x** [MrWolfZ/ngrx-forms#68]
as description

if my array has 1 item, and I remove it, the array became pristine.

I've already found a possible solution, and submitting a PR

**Comment by lucax88x** [comment]
@MrWolfZ  any updates? Thanks.

**Comment by MrWolfZ** [comment]
Hi have already long implemented this for version 3 but that release is still waiting for TypeScript 2.8 support from Angular (see https://github.com/angular/angular/issues/23779).

**Comment by MrWolfZ** [comment]
Sorry for the long delay. Sadly Angular took their time to get the support for TypeScript 2.8 out.

I have just finally released version [3.0.0](https://github.com/MrWolfZ/ngrx-forms/releases/tag/v3.0.0) which reworks the way `isDirty` is computed and should fix this issue.
