### ISSUE TITLE
No valid view adapter! when making REST Call

### ISSUE THREAD

**Issue by st-sathish** [MrWolfZ/ngrx-forms#79]
`<mat-form-field class="right-input" fxFlex="50" fxFlex.lt-md="100">
    <mat-select (click) = "getFiberOwnershipList()" [ngrxFormControlState]="(riForm$ | async).controls.fiberOwnership" placeholder="Fiber Ownership" name="fiberOwnership">
      <mat-option *ngFor="let rs of fiberOwnerships" [value]="rs.id">{{rs.text}}</mat-option>
    </mat-select>
  </mat-form-field>`
@MrWolfZ , I was displaying dropdown by making REST API call when the user click to select but before it was working when I am using tradational formControlName (angular form). I was getting "No valid view adapter" error in the console. I go through your example there you didn't make an API call. could you please give suggestion or example how to solve this issue?

**Comment by MrWolfZ** [comment]
See this issue: https://github.com/MrWolfZ/ngrx-forms/issues/62

**Comment by st-sathish** [comment]
works perfectly!!! thanks a lot
