### ISSUE TITLE
setValue should accept partial value

### ISSUE THREAD

**Issue by DerekLiang** [MrWolfZ/ngrx-forms#8]
The setValue function definition was defined as the following:
```
export declare function setValue<TValue>(value: TValue): ProjectFn<AbstractControlState<TValue>>;
export declare function setValue<TValue>(value: TValue, state: AbstractControlState<TValue>): AbstractControlState<TValue>;
```

However it  will be better to provide partial values, so the definition can be rewrite as the following (added Partial):
```
export declare function setValue<TValue>(value: Partial<TValue>): ProjectFn<AbstractControlState<TValue>>;
export declare function setValue<TValue>(value: Partial<TValue>, state: AbstractControlState<TValue>): AbstractControlState<TValue>;
```

**Comment by MrWolfZ** [comment]
@DerekLiang the `setValue` function does not really take a partial object. If you want some form control to be optional you need to make that explicit in your form value's interface. The reason for this is that other parts of the ngrx-forms API could fail (either at compile- or at run-time) if only a partial form group was present. For example the `validate` update function takes a function that is given the form value as a parameter. If some control of a group did not exist even though the form value interface indicates it always does then this opens the door for run-time failures.
