### ISSUE TITLE
Handle material-form error <mat-error>

### ISSUE THREAD

**Issue by st-sathish** [MrWolfZ/ngrx-forms#82]
@MrWolfZ , Could you please tell me or give a proper example to handle mat-error? I have concern to move validation error to store since the developer must have knowledge in ngrx to handle this error. what am suggesting is to display validation error in an exising way (html) so that the develop who has basic knowledge can do a valiation in the form. I'm using code to display <mat-error> but it's not working. I looked at your material-example and it is implemented is quite different from us.

`<mat-error *ngIf="(rdForm$ | async).controls.routeId.errors.pattern"> Route Id should be <strong>number</strong></mat-error>`

This is our reducer
-------------------
```
export const validateForm = createFormGroupReducerWithUpdate<MyRoutesRootForm>({
  details: updateGroup<MyRouteDetailsForm>({
    routeName: validate(required),
    routeId: validate(required),
  })
});
```

```
export function reducer(state = initialState, action: MyRoutesActions): MyRoutesFormState {
  let form = formGroupReducer(state.form, action);
  form = validateForm(form, action);
  if (form !== state.form) {
    state = { ...state, form };
  }
  switch (action.type) {
    case ADD_MY_ROUTE_DETAIL_FORM:
      return state;
    default:
      return state;
  }
}
```

and the component code:
-----------------------
```
public rdForm$: Observable<FormGroupState<MyRouteDetailsForm>>;

constructor(
    private store: Store<fromRoot.AppState>
  ) {
    this.rdForm$ = this.store.select(state => <FormGroupState<MyRouteDetailsForm>>state.myRoutes.form.controls.details);
  }
```

**Comment by MrWolfZ** [comment]
The code you posted looks correct to me. Are you using the material module from the example app including the custom error state matcher? The most common reason for mat-error not being shown is that the form field does not know it is in an error state which you can do with the error state matcher from the example app. Also, which version of material are you using?

**Comment by st-sathish** [comment]
we are using material version - 5.0.0-rc0. @MrWolfZ could you please explain the little bit more about error state matcher or give an example link because we imported MaterialModule suggested by your example and in the form, we are using ngrxFormControlState. see the below code
```
<mat-form-field class="left-input" fxFlex="50" fxFlex.lt-md="100">
          <input matInput placeholder="Route Name" name="routeName" [ngrxFormControlState]="rdForm$.controls.routeName" required>
          <mat-error *ngIf="rdForm$.errors._routeName?.required"> Route Name is <strong>required</strong></mat-error>
        </mat-form-field>
```
Question:
1: The error state matcher will automatically popup when we included [ngrxFormControlState]?
2. In the mat-error, I was using `rdForm$.errors._routeName?.required` I saw in your example code but the IDE (WebStorm) was showing like routeName is undefined and I can see errors object has only ValidationError object. Is this correct? please give solution about handing error object.
3. Can I remove ngrx-forms validationForm function and keep html level mat-error validation? I think the validationForm function is not necessary in the reducer to enable mat-error validation. need any one rite?

**Comment by MrWolfZ** [comment]
Angular material needs to be able to figure out when a form control should be shown in an error state. For this they have the concept of an error state matcher. However, sadly they have hardcoded this to only work with `@angular/forms`. Therefore we need to do a kind of hack. The error state matcher from the example material module does this for **ngrx-forms** and should automatically get applied to all material inputs that have an `[ngrxFormControlState]` attribute as long as the module declaring the error state matcher is correctly imported into the module containing the form.

So to answer your specific questions:

1. Yes, as explained above it should automatically get applied
2. You should be able to use both `(rdForm$ | async).errors._routeName?.required` and `(rdForm$ | async).controls.routeName.errors.required`. I recommend the second one. The reason the IDE is complaining is that in the current version of **ngrx-forms** the ValidationError object is not properly typed. With the next version the IDE will know that `(rdForm$ | async).controls.routeName.errors.required` exists but not the other one sadly.
3. I am not sure what you mean by html-level validation. With **ngrx-forms** you always have the validation in the reducer. The `mat-error` is just displaying that error.

As I mentioned before your code looks correct to me. What is the concrete behaviour you see? Is the form field turning red but no error is showing? Or is it not turning red at all? For debugging the state you can just put a `<pre>{{ rdForm$ | async }}</pre>` somewhere in the HTML to see live how the form state looks and whether your validation is correctly applied.

**Comment by st-sathish** [comment]
wow, validations are working perfectly!!! Thank you @MrWolfZ. For 3rd point, I expect that formControlState in angular form will take HTML attribute (pattern, required) for validation and I expect the same behavior in the ngrx-forms for validation. But it was in the reverse. I understood from your previous comment that the ngrx-forms need validation in the store to show the mat-error message, not in the HTML attribute (pattern, required) correct? correct me If am wrong.

**Comment by MrWolfZ** [comment]
You are indeed correct. Since everything in **ngrx-forms** is done in pure reducers you cannot use the `pattern` or `required` attributes in HTML. The main advantage of this is that your code becomes much easier to test and maintain.

**Comment by st-sathish** [comment]
Thank you @MrWolfZ, much appreciated, Good Job for instant reply!!!. I'm interested to do a contribution what should I do?

**Comment by MrWolfZ** [comment]
Currently there are no open tasks. I will soon release version 3 after which there may be some new feature requests or bug reports. So I suggest you simply monitor this repo's issues and you can contribute a bugfix if someone reports an issue.

Of course if you have an idea for a new feature yourself feel free to create a PR.

For now I'll close this issue. If you have any more questions please open a new one.

**Comment by codemasterover9000** [comment]
Hi, 

I have the exact same issue. I have removed the required attributes from the inputs in the html but still no visible validation. The ngrx form state is correct but the UI is not updated accordingly.

Am I missing something else?

Thanks!

**Comment by codemasterover9000** [comment]
You are right, missed the material module in the other directory. It works now. Thanks!
