### ISSUE TITLE
Migrate to rxjs-6 and new angular version dependency

### ISSUE THREAD

**Issue by jimjaeger** [MrWolfZ/ngrx-forms#91]
Angular 6 introduced dependency to rxjs-6. Can you update to rxjs-6?
Do you need help for?

**Comment by jimjaeger** [comment]
Just recognized you already updated in dev branch. When do you plan to release the changes?

**Comment by MrWolfZ** [comment]
I am waiting already some time for Angular to be made compatible with TypeScript 2.8+. That is already done for 6.1.X but I am still waiting for the final version to be released. However, I will very likely release v3.0.0 tomorrow and add a dependency on the proper rc of 6.1. I'll close this issue once I have released it.

**Comment by MrWolfZ** [comment]
I have just released version [3.0.0](https://github.com/MrWolfZ/ngrx-forms/releases/tag/v3.0.0) which updates the rxjs dependency version.

**Comment by jimjaeger** [comment]
thanks a lot
