### ISSUE TITLE
Error when upgrading to latest version

### ISSUE THREAD

**Issue by jacqui932** [MrWolfZ/ngrx-forms#92]
Hi,

I have just tried to upgrade to the latest and greatest version and I am getting this error.  Have tried deleting node_modules but no luck:

ERROR in node_modules/ngrx-forms/validation/src/required-false.d.ts(7,9): error TS2717: Subsequent property declarations must have the same type.  Property 'required' must be of type 'RequiredValidationError<any>', but here has type 'RequiredFalseValidationError'.
node_modules/ngrx-forms/validation/src/required-true.d.ts(7,9): error TS2717: Subsequent property declarations must have the same type.  Property 'required' must be of type 'RequiredValidationError<any>', but here has type 'RequiredTrueValidationError'.

Any ideas?

Cheers,
Jacqui

**Comment by MrWolfZ** [comment]
Indeed, I did not notice this since I tend to use `skipLibCheck: true` in my projects (including the example app). I have just released version [3.0.1](https://github.com/MrWolfZ/ngrx-forms/releases/tag/v3.0.1) which fixed this issue. Sorry for the inconvenience.

**Comment by jacqui932** [comment]
No problem - thanks for releasing the fix so quickly 👍
