### ISSUE TITLE
does 3.0.0 work on 6.0.9?

### ISSUE THREAD

**Issue by agalazis** [MrWolfZ/ngrx-forms#93]
considering that 6.1.0 is still rc what would block me from using ngrx forms 3.0.0 on 6.0.9?

**Comment by MrWolfZ** [comment]
Well, it will work just fine with Angular itself but it requires TypeScript 2.8+. 6.0.9 is not officially compatible with such TypeScript versions but it may still work depending on what your application does. I myself have used TypeScript 2.8 successfully with Angular 5.2.9 but I cannot guarantee that there will be no issues. Therefore feel free to try it out on your own risk.

Sadly I did miscalculate on how long it would take Angular to become compatible to TypeScript 2.8 and I had built almost all changes for 3.0.0 on top of the type inference changes so it was too much work to create a version of 3.0.0 that would not require TypeScript 2.8 :(
