### ISSUE TITLE
required validation seems to stop working in v3 for number type

### ISSUE THREAD

**Issue by bartes** [MrWolfZ/ngrx-forms#94]
hey

for `input type="number"` and 
```
export class RiskMappingForm {
  risk: number;
}
```
required validation does not work
 in opposite to greaterThanOrEqualTo which works like a charm

<img width="353" alt="screen shot 2018-07-24 at 01 19 07" src="https://user-images.githubusercontent.com/93064/43107970-aee74404-8edf-11e8-80ff-f6dce5eb90a3.png">

it worked in 2.x version though.

does `required` work only for strings?

Thanks for help in advance

**Comment by MrWolfZ** [comment]
Indeed, that is a regression (typical case of missing tests for edge cases). I have just released version [3.0.2](https://github.com/MrWolfZ/ngrx-forms/releases/tag/v3.0.2) which contains a fix for this bug. Thank you for reporting this.
