### ISSUE TITLE
Support validation for Boxed values 

### ISSUE THREAD

**Issue by dron8552** [MrWolfZ/ngrx-forms#96]
Now there is no validation function that supports Boxed value validation.

**Comment by MrWolfZ** [comment]
Indeed, your are absolutely right. I completely missed this. I'll add support for boxed values to all validation functions where it makes sense (i.e. required, etc.) with the next minor version update. Until then you call always wrap the validation functions and call `unbox` yourself, i.e.

```typescript
const validateForm = updateGroup<MyFormValue>({
  myBoxedObject: validate(value => required(unbox(value))),
});
```

**Comment by MrWolfZ** [comment]
Holy hell, half a year has already passed. I just released support for validation of boxed values in the latest release (wanted to still do this in 2018 ;) ).
