### ISSUE TITLE
updateGroup function takes a FormGroupState<T>?

### ISSUE THREAD

**Issue by MartinAskestad** [MrWolfZ/ngrx-forms#97]
When I try to add validation to my form, i use the updateGroup function as described in the documentation, but typescript tells me it takes a FormGroupState<T> rather than just T, so I can't set my rules.

```
export interface ReviewForm {
  occupation: string;
}

export const validateAndUpdateForm = updateGroup<ReviewForm>({
  occupation: validate(required)
});

```
Typescript tells me "Object literal may only specify known properties and occupation does not exist in FormGroupState<ReviewForm>".

I'm using version 2.3.6 and I can't quite figure out how to proceed.

**Comment by MrWolfZ** [comment]
Which version are you using? In pre-v3 you will have to change your code to explicitly declare the property type for the `validate` call, i.e. `occupation: validate<string>(required)`. The reason you get that error is that there is an overload on `updateGroup` that takes the form state as the first parameter and if typescript cannot match the overload it defaults to the first one. With v3 your code should work without issues.

**Comment by MartinAskestad** [comment]
Thank you, that seems to work.
